In [1]:
import sys
import os

sys.path.append(os.path.abspath("20260405-172134/f1_prediction"))
print(os.path.abspath("20260405-172134/f1_prediction"))
print(os.listdir("20260405-172134/f1_prediction")[:20])

/datasets/_deepnote_work/20260405-172134/f1_prediction
['.DS_Store', '__pycache__', 'data_loader.py', 'feature_engineering.py', 'main.py', 'output', 'quali_model.py', 'race_simulation.py', 'requirements.txt', 'standings.py']

In [2]:
from data_loader import (
    load_master_data,
    load_all_priors,
    load_2026_all_laptimes,
    load_2026_qualifying_results,
)

from feature_engineering import (
    build_training_features,
    build_2026_features,
    compute_2026_pace_signals,
    aggregate_2026_pace,
)

from quali_model import QualiModel, predict_all_grids
from race_simulation import simulate_race, simulate_season, expected_points_from_simulation
from standings import compute_expected_standings

[INFO] LightGBM/XGBoost unavailable. Using scikit-learn GradientBoosting.

In [3]:
master = load_master_data(min_year=2018)
priors = load_all_priors()
laps_2026 = load_2026_all_laptimes()
aus_q_results = load_2026_qualifying_results()

print("master shape:", master.shape)
print("driver priors:", priors["driver_priors"].shape)
print("team priors:", priors["team_priors"].shape)
print("2026 laps:", laps_2026.shape)
print("AUS quali:", aus_q_results.shape)

[INFO] Master dataset not found – building from converted_json CSVs.
[WARNING] converted_json not found either – no historical training data.
[WARNING] 2026 data directory not found: /datasets/_deepnote_work/20260405-172134/2026 cleaned
master shape: (0, 0)
driver priors: (0, 0)
team priors: (0, 0)
2026 laps: (0, 0)
AUS quali: (0, 0)

In [4]:
pace_per_session = compute_2026_pace_signals(laps_2026)
pace_2026 = aggregate_2026_pace(pace_per_session)

print("pace_per_session:", pace_per_session.shape)
print("pace_2026:", pace_2026.shape)
pace_2026.head()

pace_per_session: (0, 0)
pace_2026: (0, 3)

Empty DataFrame
Columns: [driver, pace_2026_quali, pace_2026_race]
Index: []

In [5]:
import pandas as pd

BASE = "f1_cleaned_output/priors"

priors = {
    "driver_priors": pd.read_csv(f"{BASE}/driver_priors_2026.csv"),
    "team_priors": pd.read_csv(f"{BASE}/team_priors_2026.csv"),
    "engine_priors": pd.read_csv(f"{BASE}/engine_priors_2026.csv"),
    "track_priors": pd.read_csv(f"{BASE}/track_priors_2026.csv"),
    "reliability_priors": pd.read_csv(f"{BASE}/reliability_priors_2026.csv"),
    "upgrade_priors": pd.read_csv(f"{BASE}/upgrade_priors_2026.csv"),
    "team_engine_map": pd.read_csv(f"{BASE}/team_engine_map_2026.csv"),
    "driver_team_map": pd.read_csv(f"{BASE}/driver_team_map_2026.csv"),
    "weather": pd.read_csv("weather_all_tracks.csv"),
}

print(priors["driver_priors"].shape)
print(priors["team_priors"].shape)
print(priors["driver_priors"].head())
print(priors["team_priors"].head())

(22, 10)
(11, 11)
            driver             team  quali_skill  race_skill  wet_skill  \
0   Max Verstappen  Red Bull Racing         0.99        0.99       0.97
1      Isak Hadjar  Red Bull Racing         0.86        0.88       0.82
2     Lando Norris          McLaren         0.90        0.93       0.93
3    Oscar Piastri          McLaren         0.93        0.95       0.90
4  Charles Leclerc          Ferrari         1.00        0.97       0.92

   tyre_management  start_skill  overtake_skill  defense_skill  consistency
0             0.97         0.93            0.97           0.97         0.98
1             0.83         0.85            0.84           0.83         0.85
2             0.94         0.92            0.93           0.92         0.92
3             0.92         0.92            0.91           0.91         0.90
4             0.94         1.00            0.97           0.96         0.97
              team engine_supplier  base_race_pace  base_quali_pace  \
0          McLaren        Mercedes            0.90             0.92
1          Ferrari         Ferrari            0.98             0.94
2         Mercedes        Mercedes            1.00             1.00
3  Red Bull Racing   Red Bull Ford            0.85             0.84
4     Aston Martin           Honda            0.64             0.63

   drag_efficiency  downforce_quality  weight_readiness  upgrade_potential  \
0             0.90               0.88              0.90               0.86
1             0.98               0.97              1.00               0.98
2             0.92               0.95              1.00               0.92
3             0.84               0.84              0.78               0.92
4             0.64               0.66              0.62               0.78

   strategy_quality  reliability_base  pit_stop_quality
0              0.90              0.90              0.94
1              0.86              0.97              0.98
2              0.98              0.97              0.97
3              0.92              0.78              0.93
4              0.89              0.88              0.92

In [6]:
features_2026 = build_2026_features(
    driver_priors=priors["driver_priors"],
    team_priors=priors["team_priors"],
    engine_priors=priors["engine_priors"],
    track_priors=priors["track_priors"],
    reliability_priors=priors["reliability_priors"],
    upgrade_priors=priors["upgrade_priors"],
    team_engine_map=priors["team_engine_map"],
    driver_team_map=priors["driver_team_map"],
    weather=priors["weather"],
    pace_2026=pace_2026,
)

print("features_2026:", features_2026.shape)
features_2026.head()

features_2026: (484, 47)

,round,circuit,driver,team,engine_supplier,driver_strength,wet_strength,race_skill,tyre_mgmt,start_skill,...,dnf_stress,street_factor,weather_variability,laps,avg_temp,rain_flag,temp_norm,pace_x_power,pace_x_downforce,wet_x_rain
0,1,Australia,Max Verstappen,Red Bull Racing,Red Bull Ford,0.99,0.97,0.99,0.97,0.93,...,0.45,0.4,0.5,58,10.904167,1.0,0.272604,0.504,0.588,0.97
1,1,Australia,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.86,0.82,0.88,0.83,0.85,...,0.45,0.4,0.5,58,10.904167,1.0,0.272604,0.504,0.588,0.82
2,1,Australia,Lando Norris,McLaren,Mercedes,0.90,0.93,0.93,0.94,0.92,...,0.45,0.4,0.5,58,10.904167,1.0,0.272604,0.552,0.616,0.93
3,1,Australia,Oscar Piastri,McLaren,Mercedes,0.93,0.90,0.95,0.92,0.92,...,0.45,0.4,0.5,58,10.904167,1.0,0.272604,0.552,0.616,0.90
4,1,Australia,Charles Leclerc,Ferrari,Ferrari,1.00,0.92,0.97,0.94,1.00,...,0.45,0.4,0.5,58,10.904167,1.0,0.272604,0.564,0.679,0.92

In [7]:
train_df = build_training_features(
    master=master,
    track_priors=priors["track_priors"],
    pace_2026=pace_2026,
)

print("train_df:", train_df.shape)
train_df.head()

train_df: (0, 0)

Empty DataFrame
Columns: []
Index: []

In [8]:
qm = QualiModel()
qm.train(train_df, verbose=True)

[WARNING] No training data – will use prior + 2026 scoring.

In [9]:
known_grids = {}
if not aus_q_results.empty:
    known_grids[1] = aus_q_results

all_quali = predict_all_grids(
    qm,
    features_2026,
    seed=2026,
    known_grids=known_grids,
)

print("all_quali:", all_quali.shape)
all_quali.head(20)

all_quali: (484, 10)

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,George Russell,Mercedes,Mercedes,1.046562,1,Australia,1,1.0,10.904167,0.5
1,Kimi Antonelli,Mercedes,Mercedes,1.019292,2,Australia,1,1.0,10.904167,0.5
2,Lewis Hamilton,Ferrari,Ferrari,1.018664,3,Australia,1,1.0,10.904167,0.5
3,Charles Leclerc,Ferrari,Ferrari,1.009957,4,Australia,1,1.0,10.904167,0.5
4,Oscar Piastri,McLaren,Mercedes,0.999006,5,Australia,1,1.0,10.904167,0.5
5,Max Verstappen,Red Bull Racing,Red Bull Ford,0.979171,6,Australia,1,1.0,10.904167,0.5
6,Lando Norris,McLaren,Mercedes,0.965136,7,Australia,1,1.0,10.904167,0.5
7,Carlos Sainz,Williams,Mercedes,0.961960,8,Australia,1,1.0,10.904167,0.5
8,Oliver Bearman,Haas,Ferrari,0.951552,9,Australia,1,1.0,10.904167,0.5
9,Franco Colapinto,Alpine,Mercedes,0.949496,10,Australia,1,1.0,10.904167,0.5
10,Pierre Gasly,Alpine,Mercedes,0.947948,11,Australia,1,1.0,10.904167,0.5
11,Esteban Ocon,Haas,Ferrari,0.946714,12,Australia,1,1.0,10.904167,0.5
12,Nico Hulkenberg,Audi,Audi,0.940052,13,Australia,1,1.0,10.904167,0.5
13,Alex Albon,Williams,Mercedes,0.935031,14,Australia,1,1.0,10.904167,0.5
14,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.931850,15,Australia,1,1.0,10.904167,0.5
15,Gabriel Bortoleto,Audi,Audi,0.907921,16,Australia,1,1.0,10.904167,0.5
16,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.899160,17,Australia,1,1.0,10.904167,0.5
17,Sergio Perez,Cadillac,Ferrari,0.892968,18,Australia,1,1.0,10.904167,0.5
18,Liam Lawson,Racing Bulls,Red Bull Ford,0.886772,19,Australia,1,1.0,10.904167,0.5
19,Fernando Alonso,Aston Martin,Honda,0.872372,20,Australia,1,1.0,10.904167,0.5

In [10]:
round_1 = simulate_race(
    features_2026=features_2026,
    round_num=1,
    n_simulations=3000,
    seed=2026,
    qualifying_grid=all_quali,
)

round_1["summary"].head(22)

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.2557,0.6193,0.9417,0.0570,3.96
1,2,Kimi Antonelli,Mercedes,0.2343,0.6180,0.9377,0.0607,4.08
2,3,Charles Leclerc,Ferrari,0.1940,0.5443,0.9653,0.0327,3.99
3,4,Lewis Hamilton,Ferrari,0.1833,0.5640,0.9627,0.0343,3.93
4,5,Oscar Piastri,McLaren,0.0500,0.2523,0.8990,0.0877,6.29
5,6,Lando Norris,McLaren,0.0460,0.2133,0.8957,0.0853,6.52
6,7,Max Verstappen,Red Bull Racing,0.0323,0.1480,0.8143,0.1620,8.07
7,8,Carlos Sainz,Williams,0.0020,0.0223,0.7203,0.1063,9.66
8,9,Oliver Bearman,Haas,0.0017,0.0070,0.5457,0.1270,11.27
9,10,Pierre Gasly,Alpine,0.0003,0.0053,0.5240,0.1100,11.27
10,11,Isak Hadjar,Red Bull Racing,0.0003,0.0010,0.2910,0.1520,13.25
11,12,Sergio Perez,Cadillac,0.0000,0.0000,0.0927,0.1637,15.32
12,13,Franco Colapinto,Alpine,0.0000,0.0007,0.2113,0.1153,13.71
13,14,Arvid Lindblad,Racing Bulls,0.0000,0.0000,0.0863,0.1717,15.52
14,15,Liam Lawson,Racing Bulls,0.0000,0.0000,0.0463,0.1470,16.16
15,16,Gabriel Bortoleto,Audi,0.0000,0.0000,0.1523,0.2147,14.84
16,17,Esteban Ocon,Haas,0.0000,0.0010,0.3643,0.1320,12.55
17,18,Alex Albon,Williams,0.0000,0.0030,0.4020,0.1020,12.14
18,19,Nico Hulkenberg,Audi,0.0000,0.0003,0.1090,0.2317,15.48
19,20,Lance Stroll,Aston Martin,0.0000,0.0000,0.0000,0.3863,19.67
20,21,Fernando Alonso,Aston Martin,0.0000,0.0000,0.0033,0.3767,18.61
21,22,Valtteri Bottas,Cadillac,0.0000,0.0000,0.0350,0.1787,16.71

In [11]:
driver_pts = expected_points_from_simulation(round_1, n_simulations=3000)
driver_pts.head(15)

               driver  expected_points
0      George Russell           15.853
1      Kimi Antonelli           15.585
2      Lewis Hamilton           14.920
3     Charles Leclerc           14.786
4       Oscar Piastri            9.967
5        Lando Norris            9.448
6      Max Verstappen            7.756
7        Carlos Sainz            3.893
8      Oliver Bearman            2.201
9        Pierre Gasly            2.105
10         Alex Albon            1.352
11       Esteban Ocon            1.217
12        Isak Hadjar            0.892
13   Franco Colapinto            0.646
14  Gabriel Bortoleto            0.428

In [12]:
season_results = {}

for rnd in sorted(features_2026["round"].unique()):
    print(f"Simulating round {rnd}...")

    race_result = simulate_race(
        features_2026=features_2026,
        round_num=rnd,
        n_simulations=1000,
        seed=2026 + rnd,
        qualifying_grid=all_quali,
    )

    season_results[rnd] = race_result

Simulating round 1...
Simulating round 2...
Simulating round 3...
Simulating round 4...
Simulating round 5...
Simulating round 6...
Simulating round 7...
Simulating round 8...
Simulating round 9...
Simulating round 10...
Simulating round 11...
Simulating round 12...
Simulating round 13...
Simulating round 14...
Simulating round 15...
Simulating round 16...
Simulating round 17...
Simulating round 18...
Simulating round 19...
Simulating round 20...
Simulating round 21...
Simulating round 22...

In [13]:
ROUND_TO_VIEW = 1
DRIVER_TO_VIEW = "Max Verstappen"
TEAM_TO_VIEW = "Mercedes"

In [15]:
print(f"Driver View: {DRIVER_TO_VIEW}")

driver_probs = []
for rnd in sorted(k for k in season_results.keys() if isinstance(k, int)):
    probs = season_results[rnd].get("probabilities", pd.DataFrame())
    if probs.empty:
        continue
    row = probs[probs["driver"] == DRIVER_TO_VIEW].copy()
    if not row.empty:
        row["round"] = rnd
        driver_probs.append(row)

if driver_probs:
    driver_probs_df = pd.concat(driver_probs, ignore_index=True)
    cols = [c for c in [
        "round",
        "driver",
        "team",
        "win_prob",
        "podium_prob",
        "top5_prob",
        "points_prob",
        "dnf_prob",
        "expected_pos"
    ] if c in driver_probs_df.columns]
    display(driver_probs_df[cols].sort_values("round").reset_index(drop=True))
else:
    print("No driver probability rows found.")

Driver View: Max Verstappen
No driver probability rows found.

In [16]:
ROUND_TO_VIEW = 3

In [17]:
print(f"ROUND {ROUND_TO_VIEW} QUALIFYING")
display(
    all_quali[all_quali["round"] == ROUND_TO_VIEW]
    .sort_values("quali_pos")
    .reset_index(drop=True)
)

ROUND 3 QUALIFYING

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Charles Leclerc,Ferrari,Ferrari,1.073588,1,Japan,3,1.0,24.425,0.55
1,Kimi Antonelli,Mercedes,Mercedes,1.055791,2,Japan,3,1.0,24.425,0.55
2,George Russell,Mercedes,Mercedes,1.021716,3,Japan,3,1.0,24.425,0.55
3,Oscar Piastri,McLaren,Mercedes,1.018514,4,Japan,3,1.0,24.425,0.55
4,Lando Norris,McLaren,Mercedes,0.996248,5,Japan,3,1.0,24.425,0.55
5,Carlos Sainz,Williams,Mercedes,0.970267,6,Japan,3,1.0,24.425,0.55
6,Gabriel Bortoleto,Audi,Audi,0.958533,7,Japan,3,1.0,24.425,0.55
7,Lewis Hamilton,Ferrari,Ferrari,0.955633,8,Japan,3,1.0,24.425,0.55
8,Max Verstappen,Red Bull Racing,Red Bull Ford,0.954484,9,Japan,3,1.0,24.425,0.55
9,Franco Colapinto,Alpine,Mercedes,0.948696,10,Japan,3,1.0,24.425,0.55
10,Esteban Ocon,Haas,Ferrari,0.936049,11,Japan,3,1.0,24.425,0.55
11,Alex Albon,Williams,Mercedes,0.932642,12,Japan,3,1.0,24.425,0.55
12,Oliver Bearman,Haas,Ferrari,0.924259,13,Japan,3,1.0,24.425,0.55
13,Nico Hulkenberg,Audi,Audi,0.917114,14,Japan,3,1.0,24.425,0.55
14,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.904057,15,Japan,3,1.0,24.425,0.55
15,Pierre Gasly,Alpine,Mercedes,0.903559,16,Japan,3,1.0,24.425,0.55
16,Liam Lawson,Racing Bulls,Red Bull Ford,0.898237,17,Japan,3,1.0,24.425,0.55
17,Sergio Perez,Cadillac,Ferrari,0.890660,18,Japan,3,1.0,24.425,0.55
18,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.885039,19,Japan,3,1.0,24.425,0.55
19,Valtteri Bottas,Cadillac,Ferrari,0.847605,20,Japan,3,1.0,24.425,0.55
20,Fernando Alonso,Aston Martin,Honda,0.801814,21,Japan,3,1.0,24.425,0.55
21,Lance Stroll,Aston Martin,Honda,0.794068,22,Japan,3,1.0,24.425,0.55

In [18]:
print(f"ROUND {ROUND_TO_VIEW} RACE SUMMARY")
display(season_results[ROUND_TO_VIEW]["summary"])

ROUND 3 RACE SUMMARY

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.258,0.642,0.936,0.063,3.98
1,2,George Russell,Mercedes,0.255,0.613,0.941,0.057,3.99
2,3,Charles Leclerc,Ferrari,0.244,0.636,0.957,0.042,3.68
3,4,Lewis Hamilton,Ferrari,0.124,0.483,0.970,0.029,4.23
4,5,Lando Norris,McLaren,0.054,0.235,0.904,0.093,6.34
5,6,Oscar Piastri,McLaren,0.047,0.235,0.909,0.080,6.16
6,7,Max Verstappen,Red Bull Racing,0.016,0.120,0.823,0.150,8.18
7,8,Oliver Bearman,Haas,0.001,0.007,0.503,0.152,11.65
8,9,Alex Albon,Williams,0.001,0.004,0.410,0.109,12.09
9,10,Sergio Perez,Cadillac,0.000,0.000,0.096,0.178,15.36
10,11,Franco Colapinto,Alpine,0.000,0.000,0.205,0.144,13.78
11,12,Pierre Gasly,Alpine,0.000,0.000,0.422,0.127,12.19
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.052,0.181,16.05
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.037,0.174,16.25
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.290,0.224,13.65
15,16,Esteban Ocon,Haas,0.000,0.000,0.402,0.154,12.43
16,17,Carlos Sainz,Williams,0.000,0.023,0.761,0.101,9.26
17,18,Isak Hadjar,Red Bull Racing,0.000,0.002,0.255,0.158,13.46
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.091,0.256,15.64
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.398,19.51
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.003,0.390,18.56
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.033,0.182,16.57

In [19]:
print(f"Team View: {TEAM_TO_VIEW}")

team_probs = []

for rnd in sorted(k for k in season_results.keys() if isinstance(k, int)):
    probs = season_results[rnd].get("probabilities", pd.DataFrame())
    if probs.empty:
        continue

    rows = probs[probs["team"] == TEAM_TO_VIEW].copy()
    if not rows.empty:
        rows["round"] = rnd
        team_probs.append(rows)

if team_probs:
    team_probs_df = pd.concat(team_probs, ignore_index=True)

    cols = [c for c in [
        "round",
        "driver",
        "team",
        "win_prob",
        "podium_prob",
        "top5_prob",
        "points_prob",
        "dnf_prob",
        "expected_pos"
    ] if c in team_probs_df.columns]

    display(
        team_probs_df[cols]
        .sort_values(["round", "expected_pos"])
        .reset_index(drop=True)
    )
else:
    print("No team probability rows found.")

Team View: Mercedes
No team probability rows found.

In [20]:
for rnd in sorted(k for k in season_results.keys() if isinstance(k, int)):
    probs = season_results[rnd].get("probabilities", pd.DataFrame())
    if not probs.empty:
        print(sorted(probs["team"].dropna().unique()))
        break

In [22]:
ROUND_TO_VIEW = 1

In [23]:
for rnd in sorted(season_results.keys()):
    print(f"\n========== ROUND {rnd} RACE SUMMARY ==========")
    summary = season_results[rnd].get("summary", pd.DataFrame())
    if not summary.empty:
        display(summary.reset_index(drop=True))
    else:
        print("No summary found.")

========== ROUND 1 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.254,0.629,0.952,0.047,3.78
1,2,George Russell,Mercedes,0.243,0.624,0.950,0.048,3.84
2,3,Lewis Hamilton,Ferrari,0.203,0.539,0.962,0.037,4.00
3,4,Charles Leclerc,Ferrari,0.186,0.569,0.970,0.027,3.82
4,5,Oscar Piastri,McLaren,0.042,0.235,0.911,0.078,6.30
5,6,Max Verstappen,Red Bull Racing,0.035,0.162,0.829,0.142,7.70
6,7,Lando Norris,McLaren,0.035,0.204,0.896,0.082,6.60
7,8,Isak Hadjar,Red Bull Racing,0.001,0.002,0.276,0.172,13.40
8,9,Carlos Sainz,Williams,0.001,0.018,0.691,0.128,10.03
9,10,Oliver Bearman,Haas,0.000,0.005,0.528,0.104,11.19
10,11,Sergio Perez,Cadillac,0.000,0.001,0.091,0.185,15.42
11,12,Franco Colapinto,Alpine,0.000,0.001,0.224,0.132,13.83
12,13,Pierre Gasly,Alpine,0.000,0.004,0.501,0.108,11.42
13,14,Arvid Lindblad,Racing Bulls,0.000,0.000,0.095,0.173,15.52
14,15,Liam Lawson,Racing Bulls,0.000,0.000,0.041,0.181,16.31
15,16,Gabriel Bortoleto,Audi,0.000,0.001,0.153,0.227,14.91
16,17,Esteban Ocon,Haas,0.000,0.004,0.399,0.127,12.35
17,18,Alex Albon,Williams,0.000,0.002,0.405,0.105,12.04
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.092,0.231,15.67
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.367,19.55
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.007,0.413,18.65
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.027,0.183,16.68

========== ROUND 2 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.269,0.626,0.942,0.057,3.96
1,2,Kimi Antonelli,Mercedes,0.268,0.662,0.942,0.056,3.80
2,3,Charles Leclerc,Ferrari,0.222,0.648,0.973,0.025,3.47
3,4,Lewis Hamilton,Ferrari,0.135,0.476,0.968,0.028,4.28
4,5,Oscar Piastri,McLaren,0.061,0.280,0.906,0.087,6.07
5,6,Lando Norris,McLaren,0.027,0.183,0.875,0.102,6.99
6,7,Max Verstappen,Red Bull Racing,0.015,0.084,0.773,0.178,8.94
7,8,Carlos Sainz,Williams,0.003,0.017,0.651,0.104,10.04
8,9,Oliver Bearman,Haas,0.000,0.009,0.526,0.137,11.34
9,10,Sergio Perez,Cadillac,0.000,0.000,0.099,0.177,15.29
10,11,Franco Colapinto,Alpine,0.000,0.001,0.246,0.127,13.42
11,12,Pierre Gasly,Alpine,0.000,0.005,0.441,0.138,12.04
12,13,Arvid Lindblad,Racing Bulls,0.000,0.001,0.172,0.175,14.44
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.052,0.176,16.04
14,15,Gabriel Bortoleto,Audi,0.000,0.001,0.121,0.226,15.29
15,16,Esteban Ocon,Haas,0.000,0.001,0.424,0.141,12.07
16,17,Alex Albon,Williams,0.000,0.005,0.378,0.117,12.20
17,18,Isak Hadjar,Red Bull Racing,0.000,0.001,0.394,0.166,12.43
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.071,0.235,16.16
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.369,19.63
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.001,0.359,18.85
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.045,0.159,16.24

========== ROUND 3 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.258,0.642,0.936,0.063,3.98
1,2,George Russell,Mercedes,0.255,0.613,0.941,0.057,3.99
2,3,Charles Leclerc,Ferrari,0.244,0.636,0.957,0.042,3.68
3,4,Lewis Hamilton,Ferrari,0.124,0.483,0.970,0.029,4.23
4,5,Lando Norris,McLaren,0.054,0.235,0.904,0.093,6.34
5,6,Oscar Piastri,McLaren,0.047,0.235,0.909,0.080,6.16
6,7,Max Verstappen,Red Bull Racing,0.016,0.120,0.823,0.150,8.18
7,8,Oliver Bearman,Haas,0.001,0.007,0.503,0.152,11.65
8,9,Alex Albon,Williams,0.001,0.004,0.410,0.109,12.09
9,10,Sergio Perez,Cadillac,0.000,0.000,0.096,0.178,15.36
10,11,Franco Colapinto,Alpine,0.000,0.000,0.205,0.144,13.78
11,12,Pierre Gasly,Alpine,0.000,0.000,0.422,0.127,12.19
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.052,0.181,16.05
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.037,0.174,16.25
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.290,0.224,13.65
15,16,Esteban Ocon,Haas,0.000,0.000,0.402,0.154,12.43
16,17,Carlos Sainz,Williams,0.000,0.023,0.761,0.101,9.26
17,18,Isak Hadjar,Red Bull Racing,0.000,0.002,0.255,0.158,13.46
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.091,0.256,15.64
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.398,19.51
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.003,0.390,18.56
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.033,0.182,16.57

========== ROUND 4 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.271,0.597,0.937,0.056,4.08
1,2,George Russell,Mercedes,0.197,0.524,0.936,0.061,4.53
2,3,Charles Leclerc,Ferrari,0.196,0.552,0.957,0.037,4.10
3,4,Lewis Hamilton,Ferrari,0.171,0.513,0.957,0.039,4.29
4,5,Max Verstappen,Red Bull Racing,0.060,0.237,0.832,0.146,7.38
5,6,Lando Norris,McLaren,0.052,0.256,0.881,0.089,6.51
6,7,Oscar Piastri,McLaren,0.052,0.258,0.880,0.097,6.59
7,8,Esteban Ocon,Haas,0.001,0.004,0.366,0.142,12.56
8,9,Sergio Perez,Cadillac,0.000,0.000,0.091,0.179,15.37
9,10,Franco Colapinto,Alpine,0.000,0.000,0.184,0.134,14.20
10,11,Pierre Gasly,Alpine,0.000,0.014,0.507,0.132,11.47
11,12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.152,0.178,14.63
12,13,Liam Lawson,Racing Bulls,0.000,0.001,0.096,0.154,15.42
13,14,Oliver Bearman,Haas,0.000,0.005,0.403,0.128,12.24
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.156,0.246,15.26
15,16,Carlos Sainz,Williams,0.000,0.031,0.702,0.100,9.73
16,17,Alex Albon,Williams,0.000,0.004,0.429,0.117,11.92
17,18,Isak Hadjar,Red Bull Racing,0.000,0.004,0.374,0.142,12.47
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.095,0.244,15.92
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.389,19.60
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.012,0.377,18.46
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.053,0.159,16.26

========== ROUND 5 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.260,0.625,0.935,0.064,4.06
1,2,George Russell,Mercedes,0.211,0.566,0.928,0.067,4.45
2,3,Charles Leclerc,Ferrari,0.210,0.587,0.975,0.023,3.73
3,4,Lewis Hamilton,Ferrari,0.177,0.480,0.956,0.037,4.33
4,5,Lando Norris,McLaren,0.054,0.263,0.891,0.090,6.44
5,6,Oscar Piastri,McLaren,0.046,0.241,0.876,0.090,6.60
6,7,Max Verstappen,Red Bull Racing,0.036,0.182,0.819,0.151,7.82
7,8,Carlos Sainz,Williams,0.004,0.029,0.663,0.113,9.95
8,9,Pierre Gasly,Alpine,0.001,0.007,0.491,0.137,11.60
9,10,Isak Hadjar,Red Bull Racing,0.001,0.008,0.361,0.180,12.72
10,11,Oliver Bearman,Haas,0.000,0.005,0.467,0.147,11.94
11,12,Sergio Perez,Cadillac,0.000,0.000,0.080,0.192,15.55
12,13,Franco Colapinto,Alpine,0.000,0.002,0.212,0.129,13.81
13,14,Arvid Lindblad,Racing Bulls,0.000,0.000,0.176,0.176,14.41
14,15,Liam Lawson,Racing Bulls,0.000,0.000,0.102,0.145,15.26
15,16,Gabriel Bortoleto,Audi,0.000,0.000,0.160,0.249,15.04
16,17,Esteban Ocon,Haas,0.000,0.002,0.367,0.157,12.82
17,18,Alex Albon,Williams,0.000,0.002,0.426,0.108,11.90
18,19,Nico Hulkenberg,Audi,0.000,0.001,0.066,0.230,15.84
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.410,19.55
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.004,0.392,18.80
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.045,0.205,16.37

========== ROUND 6 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Charles Leclerc,Ferrari,0.305,0.708,0.962,0.038,3.28
1,2,Kimi Antonelli,Mercedes,0.231,0.668,0.946,0.053,3.73
2,3,George Russell,Mercedes,0.228,0.652,0.931,0.068,3.99
3,4,Lewis Hamilton,Ferrari,0.160,0.540,0.967,0.031,3.89
4,5,Oscar Piastri,McLaren,0.046,0.239,0.896,0.095,6.11
5,6,Lando Norris,McLaren,0.018,0.116,0.884,0.083,7.10
6,7,Max Verstappen,Red Bull Racing,0.008,0.052,0.766,0.176,9.26
7,8,Pierre Gasly,Alpine,0.002,0.011,0.673,0.140,10.25
8,9,Oliver Bearman,Haas,0.002,0.008,0.652,0.125,10.34
9,10,Esteban Ocon,Haas,0.000,0.001,0.447,0.154,11.98
10,11,Sergio Perez,Cadillac,0.000,0.000,0.151,0.196,14.52
11,12,Franco Colapinto,Alpine,0.000,0.000,0.340,0.115,12.40
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.051,0.180,15.77
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.018,0.162,16.84
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.137,0.249,15.03
15,16,Carlos Sainz,Williams,0.000,0.004,0.587,0.107,10.73
16,17,Alex Albon,Williams,0.000,0.001,0.367,0.121,12.46
17,18,Isak Hadjar,Red Bull Racing,0.000,0.000,0.149,0.175,14.47
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.057,0.240,15.88
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.399,19.49
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.404,18.84
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.019,0.202,16.65

========== ROUND 7 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.287,0.678,0.931,0.067,3.90
1,2,George Russell,Mercedes,0.252,0.632,0.944,0.056,3.92
2,3,Charles Leclerc,Ferrari,0.213,0.591,0.962,0.038,3.81
3,4,Lewis Hamilton,Ferrari,0.114,0.402,0.961,0.037,4.57
4,5,Oscar Piastri,McLaren,0.080,0.354,0.933,0.066,5.30
5,6,Lando Norris,McLaren,0.041,0.216,0.918,0.075,6.21
6,7,Max Verstappen,Red Bull Racing,0.013,0.104,0.838,0.139,8.07
7,8,Esteban Ocon,Haas,0.000,0.002,0.349,0.139,12.57
8,9,Sergio Perez,Cadillac,0.000,0.000,0.050,0.183,16.07
9,10,Franco Colapinto,Alpine,0.000,0.001,0.141,0.125,14.32
10,11,Pierre Gasly,Alpine,0.000,0.006,0.646,0.129,10.60
11,12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.105,0.160,15.02
12,13,Liam Lawson,Racing Bulls,0.000,0.000,0.079,0.174,15.23
13,14,Oliver Bearman,Haas,0.000,0.001,0.481,0.129,11.77
14,15,Gabriel Bortoleto,Audi,0.000,0.001,0.131,0.207,15.02
15,16,Carlos Sainz,Williams,0.000,0.009,0.682,0.113,10.27
16,17,Alex Albon,Williams,0.000,0.003,0.461,0.111,11.70
17,18,Isak Hadjar,Red Bull Racing,0.000,0.000,0.298,0.137,13.00
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.067,0.220,15.99
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.373,19.65
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.388,19.09
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.023,0.200,16.92

========== ROUND 8 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.265,0.644,0.944,0.056,3.88
1,2,George Russell,Mercedes,0.222,0.561,0.942,0.058,4.20
2,3,Lewis Hamilton,Ferrari,0.210,0.581,0.976,0.023,3.70
3,4,Charles Leclerc,Ferrari,0.162,0.511,0.962,0.034,4.12
4,5,Oscar Piastri,McLaren,0.062,0.263,0.891,0.098,6.46
5,6,Lando Norris,McLaren,0.041,0.231,0.884,0.091,6.57
6,7,Max Verstappen,Red Bull Racing,0.036,0.176,0.825,0.159,7.82
7,8,Carlos Sainz,Williams,0.002,0.018,0.695,0.103,9.82
8,9,Oliver Bearman,Haas,0.000,0.003,0.500,0.139,11.63
9,10,Sergio Perez,Cadillac,0.000,0.000,0.096,0.215,15.59
10,11,Franco Colapinto,Alpine,0.000,0.000,0.165,0.115,14.07
11,12,Pierre Gasly,Alpine,0.000,0.006,0.514,0.138,11.46
12,13,Arvid Lindblad,Racing Bulls,0.000,0.001,0.165,0.166,14.53
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.094,0.166,15.30
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.116,0.236,15.42
15,16,Esteban Ocon,Haas,0.000,0.002,0.319,0.164,13.07
16,17,Alex Albon,Williams,0.000,0.001,0.365,0.102,12.38
17,18,Isak Hadjar,Red Bull Racing,0.000,0.002,0.422,0.182,12.47
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.083,0.251,15.96
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.402,19.48
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.003,0.406,18.71
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.039,0.173,16.33

========== ROUND 9 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.310,0.681,0.950,0.049,3.56
1,2,Kimi Antonelli,Mercedes,0.244,0.636,0.951,0.048,3.75
2,3,Lewis Hamilton,Ferrari,0.190,0.563,0.972,0.026,3.77
3,4,Charles Leclerc,Ferrari,0.151,0.534,0.969,0.030,4.01
4,5,Lando Norris,McLaren,0.057,0.257,0.893,0.093,6.35
5,6,Oscar Piastri,McLaren,0.033,0.220,0.899,0.089,6.39
6,7,Max Verstappen,Red Bull Racing,0.012,0.085,0.806,0.168,8.64
7,8,Carlos Sainz,Williams,0.002,0.009,0.658,0.099,10.21
8,9,Alex Albon,Williams,0.001,0.007,0.589,0.108,10.88
9,10,Oliver Bearman,Haas,0.000,0.000,0.401,0.131,12.20
10,11,Sergio Perez,Cadillac,0.000,0.000,0.087,0.175,15.28
11,12,Franco Colapinto,Alpine,0.000,0.000,0.240,0.127,13.41
12,13,Pierre Gasly,Alpine,0.000,0.004,0.541,0.145,11.31
13,14,Arvid Lindblad,Racing Bulls,0.000,0.000,0.065,0.172,15.68
14,15,Liam Lawson,Racing Bulls,0.000,0.000,0.043,0.180,16.16
15,16,Gabriel Bortoleto,Audi,0.000,0.000,0.110,0.223,15.29
16,17,Esteban Ocon,Haas,0.000,0.000,0.373,0.149,12.37
17,18,Isak Hadjar,Red Bull Racing,0.000,0.004,0.364,0.154,12.62
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.050,0.226,16.20
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.382,19.61
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.356,18.91
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.039,0.180,16.40

========== ROUND 10 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.283,0.663,0.938,0.061,3.82
1,2,George Russell,Mercedes,0.264,0.631,0.940,0.060,3.95
2,3,Charles Leclerc,Ferrari,0.182,0.578,0.970,0.028,3.79
3,4,Lewis Hamilton,Ferrari,0.135,0.449,0.968,0.031,4.41
4,5,Oscar Piastri,McLaren,0.072,0.308,0.896,0.087,5.96
5,6,Lando Norris,McLaren,0.044,0.226,0.892,0.087,6.45
6,7,Max Verstappen,Red Bull Racing,0.017,0.113,0.795,0.187,8.50
7,8,Oliver Bearman,Haas,0.001,0.005,0.487,0.146,11.78
8,9,Carlos Sainz,Williams,0.001,0.017,0.665,0.117,10.14
9,10,Esteban Ocon,Haas,0.001,0.001,0.313,0.147,13.00
10,11,Sergio Perez,Cadillac,0.000,0.000,0.049,0.183,16.05
11,12,Franco Colapinto,Alpine,0.000,0.000,0.166,0.130,14.02
12,13,Pierre Gasly,Alpine,0.000,0.002,0.541,0.110,11.21
13,14,Arvid Lindblad,Racing Bulls,0.000,0.000,0.170,0.172,14.37
14,15,Liam Lawson,Racing Bulls,0.000,0.000,0.083,0.161,15.29
15,16,Gabriel Bortoleto,Audi,0.000,0.001,0.145,0.235,15.00
16,17,Alex Albon,Williams,0.000,0.001,0.367,0.129,12.68
17,18,Isak Hadjar,Red Bull Racing,0.000,0.005,0.500,0.158,11.71
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.087,0.253,15.86
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.399,19.55
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.001,0.401,18.91
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.027,0.195,16.55

========== ROUND 11 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.321,0.706,0.950,0.049,3.42
1,2,Charles Leclerc,Ferrari,0.263,0.683,0.960,0.039,3.46
2,3,Kimi Antonelli,Mercedes,0.234,0.661,0.938,0.061,3.91
3,4,Oscar Piastri,McLaren,0.078,0.334,0.903,0.096,5.66
4,5,Lewis Hamilton,Ferrari,0.072,0.342,0.952,0.045,4.99
5,6,Lando Norris,McLaren,0.025,0.198,0.897,0.096,6.49
6,7,Max Verstappen,Red Bull Racing,0.005,0.050,0.802,0.152,8.88
7,8,Pierre Gasly,Alpine,0.001,0.010,0.663,0.145,10.47
8,9,Carlos Sainz,Williams,0.001,0.012,0.700,0.133,10.15
9,10,Oliver Bearman,Haas,0.000,0.002,0.483,0.128,11.62
10,11,Sergio Perez,Cadillac,0.000,0.000,0.073,0.169,15.18
11,12,Franco Colapinto,Alpine,0.000,0.000,0.232,0.147,13.36
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.029,0.152,16.18
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.013,0.158,16.90
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.166,0.227,14.56
15,16,Esteban Ocon,Haas,0.000,0.000,0.344,0.132,12.54
16,17,Alex Albon,Williams,0.000,0.000,0.393,0.120,12.13
17,18,Isak Hadjar,Red Bull Racing,0.000,0.002,0.421,0.159,12.28
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.056,0.233,15.85
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.396,19.59
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.383,18.90
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.025,0.176,16.48

========== ROUND 12 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Lewis Hamilton,Ferrari,0.275,0.692,0.973,0.026,3.25
1,2,George Russell,Mercedes,0.248,0.653,0.934,0.066,4.02
2,3,Kimi Antonelli,Mercedes,0.212,0.588,0.937,0.062,4.14
3,4,Charles Leclerc,Ferrari,0.181,0.560,0.961,0.036,3.90
4,5,Oscar Piastri,McLaren,0.037,0.188,0.901,0.086,6.53
5,6,Max Verstappen,Red Bull Racing,0.023,0.148,0.826,0.161,7.87
6,7,Lando Norris,McLaren,0.021,0.143,0.877,0.093,7.17
7,8,Carlos Sainz,Williams,0.002,0.012,0.706,0.110,9.89
8,9,Oliver Bearman,Haas,0.001,0.006,0.625,0.134,10.67
9,10,Sergio Perez,Cadillac,0.000,0.000,0.046,0.174,15.90
10,11,Franco Colapinto,Alpine,0.000,0.001,0.117,0.127,14.55
11,12,Pierre Gasly,Alpine,0.000,0.006,0.601,0.115,10.72
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.063,0.146,15.59
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.051,0.170,16.06
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.199,0.240,14.52
15,16,Esteban Ocon,Haas,0.000,0.003,0.424,0.136,12.14
16,17,Alex Albon,Williams,0.000,0.000,0.391,0.106,12.12
17,18,Isak Hadjar,Red Bull Racing,0.000,0.000,0.267,0.151,13.24
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.057,0.236,16.09
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.397,19.66
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.002,0.365,18.58
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.042,0.177,16.40

========== ROUND 13 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.281,0.632,0.939,0.061,3.97
1,2,Kimi Antonelli,Mercedes,0.280,0.639,0.928,0.072,4.04
2,3,Charles Leclerc,Ferrari,0.181,0.589,0.975,0.025,3.72
3,4,Lewis Hamilton,Ferrari,0.141,0.451,0.966,0.028,4.28
4,5,Lando Norris,McLaren,0.057,0.268,0.916,0.076,5.96
5,6,Oscar Piastri,McLaren,0.036,0.214,0.894,0.088,6.51
6,7,Max Verstappen,Red Bull Racing,0.021,0.175,0.833,0.157,7.79
7,8,Carlos Sainz,Williams,0.002,0.012,0.648,0.119,10.53
8,9,Pierre Gasly,Alpine,0.001,0.007,0.565,0.118,10.87
9,10,Oliver Bearman,Haas,0.000,0.003,0.381,0.147,12.45
10,11,Sergio Perez,Cadillac,0.000,0.000,0.036,0.180,16.35
11,12,Franco Colapinto,Alpine,0.000,0.001,0.198,0.136,13.93
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.181,0.185,14.25
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.117,0.171,14.90
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.089,0.222,15.42
15,16,Esteban Ocon,Haas,0.000,0.002,0.369,0.134,12.48
16,17,Alex Albon,Williams,0.000,0.004,0.450,0.111,11.71
17,18,Isak Hadjar,Red Bull Racing,0.000,0.002,0.447,0.153,11.99
18,19,Nico Hulkenberg,Audi,0.000,0.001,0.047,0.219,16.25
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.394,19.58
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.001,0.399,19.14
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.020,0.189,16.88

========== ROUND 14 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.286,0.683,0.945,0.054,3.65
1,2,George Russell,Mercedes,0.243,0.612,0.927,0.071,4.25
2,3,Charles Leclerc,Ferrari,0.223,0.591,0.971,0.028,3.62
3,4,Lewis Hamilton,Ferrari,0.149,0.509,0.960,0.037,4.21
4,5,Lando Norris,McLaren,0.050,0.257,0.914,0.079,6.00
5,6,Oscar Piastri,McLaren,0.029,0.197,0.876,0.108,6.82
6,7,Max Verstappen,Red Bull Racing,0.017,0.117,0.809,0.156,8.37
7,8,Oliver Bearman,Haas,0.002,0.010,0.567,0.142,11.10
8,9,Pierre Gasly,Alpine,0.001,0.009,0.551,0.112,11.04
9,10,Esteban Ocon,Haas,0.000,0.000,0.364,0.150,12.74
10,11,Sergio Perez,Cadillac,0.000,0.000,0.059,0.166,15.92
11,12,Franco Colapinto,Alpine,0.000,0.000,0.268,0.123,13.35
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.089,0.162,15.33
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.085,0.164,15.20
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.124,0.214,15.09
15,16,Carlos Sainz,Williams,0.000,0.012,0.654,0.131,10.31
16,17,Alex Albon,Williams,0.000,0.002,0.371,0.103,12.35
17,18,Isak Hadjar,Red Bull Racing,0.000,0.001,0.346,0.177,12.95
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.101,0.227,15.56
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.385,19.57
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.416,19.03
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.019,0.181,16.55

========== ROUND 15 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.268,0.616,0.942,0.057,3.96
1,2,Kimi Antonelli,Mercedes,0.259,0.637,0.942,0.055,3.90
2,3,Charles Leclerc,Ferrari,0.186,0.576,0.961,0.035,3.97
3,4,Lewis Hamilton,Ferrari,0.127,0.424,0.947,0.042,4.75
4,5,Oscar Piastri,McLaren,0.066,0.268,0.876,0.106,6.53
5,6,Lando Norris,McLaren,0.051,0.247,0.897,0.081,6.40
6,7,Max Verstappen,Red Bull Racing,0.031,0.162,0.816,0.147,7.88
7,8,Isak Hadjar,Red Bull Racing,0.005,0.012,0.492,0.145,11.62
8,9,Carlos Sainz,Williams,0.004,0.027,0.675,0.104,9.97
9,10,Pierre Gasly,Alpine,0.001,0.011,0.506,0.127,11.53
10,11,Esteban Ocon,Haas,0.001,0.003,0.293,0.158,13.05
11,12,Oliver Bearman,Haas,0.001,0.008,0.396,0.145,12.32
12,13,Liam Lawson,Racing Bulls,0.000,0.001,0.120,0.180,14.94
13,14,Sergio Perez,Cadillac,0.000,0.000,0.069,0.180,15.68
14,15,Franco Colapinto,Alpine,0.000,0.000,0.205,0.123,13.83
15,16,Arvid Lindblad,Racing Bulls,0.000,0.001,0.189,0.168,14.31
16,17,Gabriel Bortoleto,Audi,0.000,0.001,0.120,0.211,15.07
17,18,Alex Albon,Williams,0.000,0.006,0.448,0.104,11.79
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.067,0.244,16.25
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.398,19.57
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.002,0.389,18.95
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.037,0.188,16.75

========== ROUND 16 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.255,0.619,0.932,0.067,4.12
1,2,Lewis Hamilton,Ferrari,0.238,0.613,0.964,0.035,3.63
2,3,George Russell,Mercedes,0.201,0.559,0.941,0.059,4.24
3,4,Charles Leclerc,Ferrari,0.180,0.579,0.958,0.041,3.90
4,5,Lando Norris,McLaren,0.063,0.312,0.900,0.096,5.94
5,6,Oscar Piastri,McLaren,0.048,0.214,0.888,0.101,6.54
6,7,Max Verstappen,Red Bull Racing,0.010,0.070,0.790,0.173,8.94
7,8,Carlos Sainz,Williams,0.002,0.012,0.656,0.126,10.26
8,9,Oliver Bearman,Haas,0.001,0.007,0.554,0.162,11.34
9,10,Franco Colapinto,Alpine,0.001,0.001,0.317,0.124,12.79
10,11,Pierre Gasly,Alpine,0.001,0.007,0.515,0.147,11.51
11,12,Sergio Perez,Cadillac,0.000,0.000,0.111,0.185,15.11
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.090,0.167,15.30
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.028,0.189,16.73
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.115,0.245,15.40
15,16,Esteban Ocon,Haas,0.000,0.006,0.493,0.156,11.74
16,17,Alex Albon,Williams,0.000,0.001,0.271,0.113,13.09
17,18,Isak Hadjar,Red Bull Racing,0.000,0.000,0.293,0.197,13.48
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.119,0.236,15.29
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.380,19.29
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.005,0.396,18.28
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.060,0.223,16.07

========== ROUND 17 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.252,0.642,0.940,0.059,3.89
1,2,Kimi Antonelli,Mercedes,0.246,0.661,0.933,0.065,3.94
2,3,Charles Leclerc,Ferrari,0.220,0.583,0.978,0.021,3.51
3,4,Lewis Hamilton,Ferrari,0.197,0.607,0.973,0.026,3.63
4,5,Lando Norris,McLaren,0.036,0.214,0.883,0.101,6.58
5,6,Oscar Piastri,McLaren,0.031,0.175,0.903,0.082,6.63
6,7,Max Verstappen,Red Bull Racing,0.017,0.100,0.827,0.147,8.09
7,8,Carlos Sainz,Williams,0.001,0.008,0.684,0.126,10.24
8,9,Oliver Bearman,Haas,0.000,0.004,0.541,0.137,11.23
9,10,Sergio Perez,Cadillac,0.000,0.000,0.050,0.195,16.11
10,11,Franco Colapinto,Alpine,0.000,0.000,0.174,0.132,14.07
11,12,Pierre Gasly,Alpine,0.000,0.002,0.507,0.116,11.41
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.069,0.182,15.62
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.063,0.141,15.75
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.178,0.243,14.66
15,16,Esteban Ocon,Haas,0.000,0.003,0.394,0.148,12.28
16,17,Alex Albon,Williams,0.000,0.001,0.356,0.107,12.33
17,18,Isak Hadjar,Red Bull Racing,0.000,0.000,0.402,0.153,12.52
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.113,0.213,15.31
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.388,19.52
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.400,19.04
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.032,0.210,16.63

========== ROUND 18 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.265,0.670,0.939,0.060,3.84
1,2,George Russell,Mercedes,0.250,0.593,0.940,0.058,4.07
2,3,Charles Leclerc,Ferrari,0.182,0.547,0.975,0.024,3.84
3,4,Lewis Hamilton,Ferrari,0.166,0.526,0.965,0.030,4.05
4,5,Oscar Piastri,McLaren,0.063,0.259,0.895,0.099,6.30
5,6,Lando Norris,McLaren,0.037,0.197,0.880,0.102,6.78
6,7,Max Verstappen,Red Bull Racing,0.033,0.176,0.800,0.182,8.17
7,8,Carlos Sainz,Williams,0.002,0.015,0.656,0.124,10.16
8,9,Oliver Bearman,Haas,0.001,0.003,0.505,0.144,11.70
9,10,Isak Hadjar,Red Bull Racing,0.001,0.005,0.438,0.159,12.06
10,11,Sergio Perez,Cadillac,0.000,0.000,0.070,0.178,15.81
11,12,Franco Colapinto,Alpine,0.000,0.000,0.201,0.119,13.77
12,13,Pierre Gasly,Alpine,0.000,0.004,0.555,0.135,11.24
13,14,Arvid Lindblad,Racing Bulls,0.000,0.001,0.173,0.176,14.42
14,15,Liam Lawson,Racing Bulls,0.000,0.000,0.121,0.171,14.97
15,16,Gabriel Bortoleto,Audi,0.000,0.000,0.134,0.245,15.34
16,17,Esteban Ocon,Haas,0.000,0.001,0.250,0.146,13.50
17,18,Alex Albon,Williams,0.000,0.003,0.372,0.126,12.35
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.094,0.257,15.92
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.389,19.45
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.005,0.422,18.73
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.032,0.193,16.54

========== ROUND 19 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.280,0.682,0.941,0.059,3.71
1,2,Charles Leclerc,Ferrari,0.225,0.631,0.961,0.039,3.69
2,3,George Russell,Mercedes,0.217,0.641,0.936,0.061,3.99
3,4,Lewis Hamilton,Ferrari,0.194,0.531,0.956,0.041,4.09
4,5,Oscar Piastri,McLaren,0.034,0.206,0.884,0.102,6.62
5,6,Lando Norris,McLaren,0.033,0.205,0.890,0.096,6.50
6,7,Max Verstappen,Red Bull Racing,0.013,0.077,0.795,0.155,8.71
7,8,Pierre Gasly,Alpine,0.002,0.012,0.562,0.133,10.98
8,9,Esteban Ocon,Haas,0.001,0.005,0.423,0.119,11.98
9,10,Oliver Bearman,Haas,0.001,0.002,0.501,0.163,11.63
10,11,Sergio Perez,Cadillac,0.000,0.001,0.078,0.171,15.36
11,12,Franco Colapinto,Alpine,0.000,0.001,0.302,0.130,13.04
12,13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.121,0.197,15.19
13,14,Liam Lawson,Racing Bulls,0.000,0.000,0.088,0.175,15.49
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.171,0.249,15.13
15,16,Carlos Sainz,Williams,0.000,0.005,0.549,0.123,11.00
16,17,Alex Albon,Williams,0.000,0.001,0.427,0.105,11.94
17,18,Isak Hadjar,Red Bull Racing,0.000,0.000,0.304,0.170,13.17
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.069,0.233,15.99
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.390,19.53
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.383,18.89
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.042,0.182,16.37

========== ROUND 20 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,Kimi Antonelli,Mercedes,0.294,0.668,0.937,0.060,3.85
1,2,George Russell,Mercedes,0.259,0.607,0.928,0.072,4.24
2,3,Charles Leclerc,Ferrari,0.180,0.568,0.965,0.030,3.94
3,4,Lewis Hamilton,Ferrari,0.118,0.446,0.958,0.032,4.52
4,5,Oscar Piastri,McLaren,0.056,0.263,0.892,0.088,6.26
5,6,Max Verstappen,Red Bull Racing,0.044,0.196,0.828,0.146,7.51
6,7,Lando Norris,McLaren,0.041,0.209,0.891,0.086,6.71
7,8,Isak Hadjar,Red Bull Racing,0.004,0.013,0.550,0.165,11.32
8,9,Carlos Sainz,Williams,0.002,0.017,0.659,0.093,10.10
9,10,Liam Lawson,Racing Bulls,0.001,0.001,0.117,0.149,14.81
10,11,Alex Albon,Williams,0.001,0.002,0.377,0.101,12.30
11,12,Sergio Perez,Cadillac,0.000,0.000,0.050,0.177,16.03
12,13,Franco Colapinto,Alpine,0.000,0.001,0.184,0.127,14.00
13,14,Pierre Gasly,Alpine,0.000,0.008,0.533,0.113,11.17
14,15,Arvid Lindblad,Racing Bulls,0.000,0.000,0.199,0.179,14.17
15,16,Gabriel Bortoleto,Audi,0.000,0.000,0.103,0.237,15.58
16,17,Oliver Bearman,Haas,0.000,0.001,0.406,0.116,12.08
17,18,Esteban Ocon,Haas,0.000,0.000,0.312,0.143,13.05
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.079,0.224,15.88
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.370,19.63
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.001,0.377,19.11
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.031,0.171,16.72

========== ROUND 21 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.288,0.716,0.930,0.070,3.82
1,2,Kimi Antonelli,Mercedes,0.265,0.664,0.926,0.074,3.95
2,3,Charles Leclerc,Ferrari,0.219,0.624,0.961,0.039,3.66
3,4,Lewis Hamilton,Ferrari,0.169,0.535,0.965,0.034,4.02
4,5,Oscar Piastri,McLaren,0.033,0.192,0.897,0.098,6.41
5,6,Max Verstappen,Red Bull Racing,0.016,0.125,0.825,0.167,8.02
6,7,Lando Norris,McLaren,0.010,0.135,0.904,0.091,6.79
7,8,Esteban Ocon,Haas,0.000,0.000,0.277,0.148,13.18
8,9,Sergio Perez,Cadillac,0.000,0.000,0.034,0.180,16.25
9,10,Franco Colapinto,Alpine,0.000,0.000,0.220,0.104,13.38
10,11,Pierre Gasly,Alpine,0.000,0.003,0.656,0.130,10.58
11,12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.089,0.144,15.08
12,13,Liam Lawson,Racing Bulls,0.000,0.000,0.112,0.177,14.92
13,14,Oliver Bearman,Haas,0.000,0.001,0.487,0.130,11.72
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.134,0.227,14.97
15,16,Carlos Sainz,Williams,0.000,0.003,0.590,0.104,10.81
16,17,Alex Albon,Williams,0.000,0.001,0.458,0.095,11.57
17,18,Isak Hadjar,Red Bull Racing,0.000,0.001,0.458,0.131,11.92
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.061,0.251,16.12
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.424,19.68
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.001,0.365,19.00
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.015,0.175,17.12

========== ROUND 22 RACE SUMMARY ==========

,predicted_pos,driver,team,win_prob,podium_prob,points_prob,dnf_prob,expected_pos
0,1,George Russell,Mercedes,0.289,0.677,0.930,0.070,3.89
1,2,Kimi Antonelli,Mercedes,0.277,0.689,0.950,0.050,3.61
2,3,Lewis Hamilton,Ferrari,0.167,0.508,0.967,0.033,4.04
3,4,Charles Leclerc,Ferrari,0.166,0.568,0.959,0.041,3.95
4,5,Oscar Piastri,McLaren,0.053,0.232,0.925,0.069,5.89
5,6,Lando Norris,McLaren,0.043,0.224,0.918,0.073,6.06
6,7,Max Verstappen,Red Bull Racing,0.005,0.092,0.816,0.152,8.32
7,8,Esteban Ocon,Haas,0.000,0.000,0.327,0.138,12.77
8,9,Sergio Perez,Cadillac,0.000,0.000,0.040,0.163,16.00
9,10,Franco Colapinto,Alpine,0.000,0.001,0.247,0.125,13.40
10,11,Pierre Gasly,Alpine,0.000,0.000,0.549,0.119,11.26
11,12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.167,0.152,14.21
12,13,Liam Lawson,Racing Bulls,0.000,0.000,0.049,0.171,16.09
13,14,Oliver Bearman,Haas,0.000,0.001,0.512,0.134,11.53
14,15,Gabriel Bortoleto,Audi,0.000,0.000,0.120,0.225,15.18
15,16,Carlos Sainz,Williams,0.000,0.007,0.656,0.108,10.35
16,17,Alex Albon,Williams,0.000,0.001,0.349,0.098,12.41
17,18,Isak Hadjar,Red Bull Racing,0.000,0.000,0.445,0.151,12.20
18,19,Nico Hulkenberg,Audi,0.000,0.000,0.055,0.225,16.13
19,20,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.383,19.67
20,21,Fernando Alonso,Aston Martin,0.000,0.000,0.001,0.381,19.07
21,22,Valtteri Bottas,Cadillac,0.000,0.000,0.018,0.176,16.96

In [24]:
for rnd in sorted(season_results.keys()):
    print(f"\n========== ROUND {rnd} FULL PROBABILITIES ==========")
    probs = season_results[rnd].get("probabilities", pd.DataFrame())
    if not probs.empty:
        display(probs.sort_values("predicted_pos").reset_index(drop=True))
    else:
        print("No probabilities found.")

========== ROUND 1 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.254,0.629,0.853,0.952,0.047,0.254,3.78,1.011227,1
1,George Russell,Mercedes,0.243,0.624,0.851,0.950,0.048,0.243,3.84,1.010698,2
2,Lewis Hamilton,Ferrari,0.203,0.539,0.827,0.962,0.037,0.203,4.00,1.005251,3
3,Charles Leclerc,Ferrari,0.186,0.569,0.827,0.970,0.027,0.186,3.82,1.005609,4
4,Oscar Piastri,McLaren,0.042,0.235,0.531,0.911,0.078,0.042,6.30,0.980517,5
5,Max Verstappen,Red Bull Racing,0.035,0.162,0.420,0.829,0.142,0.035,7.70,0.973544,6
6,Lando Norris,McLaren,0.035,0.204,0.474,0.896,0.082,0.035,6.60,0.977640,7
7,Isak Hadjar,Red Bull Racing,0.001,0.002,0.014,0.276,0.172,0.001,13.40,0.902864,8
8,Carlos Sainz,Williams,0.001,0.018,0.088,0.691,0.128,0.001,10.03,0.938670,9
9,Oliver Bearman,Haas,0.000,0.005,0.031,0.528,0.104,0.000,11.19,0.921388,10
10,Sergio Perez,Cadillac,0.000,0.001,0.004,0.091,0.185,0.000,15.42,0.877432,11
11,Franco Colapinto,Alpine,0.000,0.001,0.006,0.224,0.132,0.000,13.83,0.892620,12
12,Pierre Gasly,Alpine,0.000,0.004,0.034,0.501,0.108,0.000,11.42,0.918914,13
13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.002,0.095,0.173,0.000,15.52,0.875589,14
14,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.041,0.181,0.000,16.31,0.864550,15
15,Gabriel Bortoleto,Audi,0.000,0.001,0.002,0.153,0.227,0.000,14.91,0.888843,16
16,Esteban Ocon,Haas,0.000,0.004,0.021,0.399,0.127,0.000,12.35,0.908919,17
17,Alex Albon,Williams,0.000,0.002,0.013,0.405,0.105,0.000,12.04,0.910361,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.002,0.092,0.231,0.000,15.67,0.879217,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.367,0.000,19.55,0.762916,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.007,0.413,0.000,18.65,0.835751,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.027,0.183,0.000,16.68,0.860156,22

========== ROUND 2 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.269,0.626,0.846,0.942,0.057,0.269,3.96,0.997102,1
1,Kimi Antonelli,Mercedes,0.268,0.662,0.858,0.942,0.056,0.268,3.80,0.998412,2
2,Charles Leclerc,Ferrari,0.222,0.648,0.872,0.973,0.025,0.222,3.47,0.994652,3
3,Lewis Hamilton,Ferrari,0.135,0.476,0.770,0.968,0.028,0.135,4.28,0.984707,4
4,Oscar Piastri,McLaren,0.061,0.280,0.611,0.906,0.087,0.061,6.07,0.973887,5
5,Lando Norris,McLaren,0.027,0.183,0.472,0.875,0.102,0.027,6.99,0.964902,6
6,Max Verstappen,Red Bull Racing,0.015,0.084,0.287,0.773,0.178,0.015,8.94,0.954498,7
7,Carlos Sainz,Williams,0.003,0.017,0.092,0.651,0.104,0.003,10.04,0.929263,8
8,Oliver Bearman,Haas,0.000,0.009,0.053,0.526,0.137,0.000,11.34,0.919576,9
9,Sergio Perez,Cadillac,0.000,0.000,0.002,0.099,0.177,0.000,15.29,0.879879,10
10,Franco Colapinto,Alpine,0.000,0.001,0.011,0.246,0.127,0.000,13.42,0.897638,11
11,Pierre Gasly,Alpine,0.000,0.005,0.029,0.441,0.138,0.000,12.04,0.912644,12
12,Arvid Lindblad,Racing Bulls,0.000,0.001,0.005,0.172,0.175,0.000,14.44,0.890202,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.002,0.052,0.176,0.000,16.04,0.869620,14
14,Gabriel Bortoleto,Audi,0.000,0.001,0.004,0.121,0.226,0.000,15.29,0.885022,15
15,Esteban Ocon,Haas,0.000,0.001,0.027,0.424,0.141,0.000,12.07,0.912221,16
16,Alex Albon,Williams,0.000,0.005,0.028,0.378,0.117,0.000,12.20,0.908884,17
17,Isak Hadjar,Red Bull Racing,0.000,0.001,0.030,0.394,0.166,0.000,12.43,0.911576,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.001,0.071,0.235,0.000,16.16,0.874405,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.369,0.000,19.63,0.760154,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.001,0.359,0.000,18.85,0.824449,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.045,0.159,0.000,16.24,0.866315,22

========== ROUND 3 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.258,0.642,0.853,0.936,0.063,0.258,3.98,1.024927,1
1,George Russell,Mercedes,0.255,0.613,0.845,0.941,0.057,0.255,3.99,1.022020,2
2,Charles Leclerc,Ferrari,0.244,0.636,0.868,0.957,0.042,0.244,3.68,1.022217,3
3,Lewis Hamilton,Ferrari,0.124,0.483,0.778,0.970,0.029,0.124,4.23,1.009378,4
4,Lando Norris,McLaren,0.054,0.235,0.547,0.904,0.093,0.054,6.34,0.992632,5
5,Oscar Piastri,McLaren,0.047,0.235,0.561,0.909,0.080,0.047,6.16,0.993870,6
6,Max Verstappen,Red Bull Racing,0.016,0.120,0.333,0.823,0.150,0.016,8.18,0.976060,7
7,Oliver Bearman,Haas,0.001,0.007,0.031,0.503,0.152,0.001,11.65,0.927310,8
8,Alex Albon,Williams,0.001,0.004,0.012,0.410,0.109,0.001,12.09,0.917752,9
9,Sergio Perez,Cadillac,0.000,0.000,0.000,0.096,0.178,0.000,15.36,0.882646,10
10,Franco Colapinto,Alpine,0.000,0.000,0.005,0.205,0.144,0.000,13.78,0.900568,11
11,Pierre Gasly,Alpine,0.000,0.000,0.009,0.422,0.127,0.000,12.19,0.917366,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.000,0.052,0.181,0.000,16.05,0.872682,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.037,0.174,0.000,16.25,0.869469,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.005,0.290,0.224,0.000,13.65,0.910111,15
15,Esteban Ocon,Haas,0.000,0.000,0.016,0.402,0.154,0.000,12.43,0.917984,16
16,Carlos Sainz,Williams,0.000,0.023,0.123,0.761,0.101,0.000,9.26,0.951629,17
17,Isak Hadjar,Red Bull Racing,0.000,0.002,0.013,0.255,0.158,0.000,13.46,0.905048,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.001,0.091,0.256,0.000,15.64,0.885608,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.398,0.000,19.51,0.765617,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.003,0.390,0.000,18.56,0.838138,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.033,0.182,0.000,16.57,0.864405,22

========== ROUND 4 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.271,0.597,0.816,0.937,0.056,0.271,4.08,1.004355,1
1,George Russell,Mercedes,0.197,0.524,0.777,0.936,0.061,0.197,4.53,0.998517,2
2,Charles Leclerc,Ferrari,0.196,0.552,0.800,0.957,0.037,0.196,4.10,0.997171,3
3,Lewis Hamilton,Ferrari,0.171,0.513,0.780,0.957,0.039,0.171,4.29,0.994580,4
4,Max Verstappen,Red Bull Racing,0.060,0.237,0.486,0.832,0.146,0.060,7.38,0.974956,5
5,Lando Norris,McLaren,0.052,0.256,0.511,0.881,0.089,0.052,6.51,0.975140,6
6,Oscar Piastri,McLaren,0.052,0.258,0.518,0.880,0.097,0.052,6.59,0.975221,7
7,Esteban Ocon,Haas,0.001,0.004,0.025,0.366,0.142,0.001,12.56,0.906966,8
8,Sergio Perez,Cadillac,0.000,0.000,0.003,0.091,0.179,0.000,15.37,0.876531,9
9,Franco Colapinto,Alpine,0.000,0.000,0.007,0.184,0.134,0.000,14.20,0.887382,10
10,Pierre Gasly,Alpine,0.000,0.014,0.047,0.507,0.132,0.000,11.47,0.918204,11
11,Arvid Lindblad,Racing Bulls,0.000,0.000,0.004,0.152,0.178,0.000,14.63,0.885790,12
12,Liam Lawson,Racing Bulls,0.000,0.001,0.002,0.096,0.154,0.000,15.42,0.873250,13
13,Oliver Bearman,Haas,0.000,0.005,0.025,0.403,0.128,0.000,12.24,0.908815,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.004,0.156,0.246,0.000,15.26,0.884337,15
15,Carlos Sainz,Williams,0.000,0.031,0.132,0.702,0.100,0.000,9.73,0.934532,16
16,Alex Albon,Williams,0.000,0.004,0.029,0.429,0.117,0.000,11.92,0.911361,17
17,Isak Hadjar,Red Bull Racing,0.000,0.004,0.029,0.374,0.142,0.000,12.47,0.908372,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.004,0.095,0.244,0.000,15.92,0.873671,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.389,0.000,19.60,0.764004,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.012,0.377,0.000,18.46,0.834596,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.001,0.053,0.159,0.000,16.26,0.861987,22

========== ROUND 5 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.260,0.625,0.823,0.935,0.064,0.260,4.06,0.996334,1
1,George Russell,Mercedes,0.211,0.566,0.786,0.928,0.067,0.211,4.45,0.991471,2
2,Charles Leclerc,Ferrari,0.210,0.587,0.824,0.975,0.023,0.210,3.73,0.990045,3
3,Lewis Hamilton,Ferrari,0.177,0.480,0.786,0.956,0.037,0.177,4.33,0.985868,4
4,Lando Norris,McLaren,0.054,0.263,0.537,0.891,0.090,0.054,6.44,0.968965,5
5,Oscar Piastri,McLaren,0.046,0.241,0.511,0.876,0.090,0.046,6.60,0.968057,6
6,Max Verstappen,Red Bull Racing,0.036,0.182,0.417,0.819,0.151,0.036,7.82,0.963577,7
7,Carlos Sainz,Williams,0.004,0.029,0.124,0.663,0.113,0.004,9.95,0.931827,8
8,Pierre Gasly,Alpine,0.001,0.007,0.054,0.491,0.137,0.001,11.60,0.916627,9
9,Isak Hadjar,Red Bull Racing,0.001,0.008,0.030,0.361,0.180,0.001,12.72,0.909447,10
10,Oliver Bearman,Haas,0.000,0.005,0.026,0.467,0.147,0.000,11.94,0.915088,11
11,Sergio Perez,Cadillac,0.000,0.000,0.003,0.080,0.192,0.000,15.55,0.876711,12
12,Franco Colapinto,Alpine,0.000,0.002,0.007,0.212,0.129,0.000,13.81,0.892598,13
13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.008,0.176,0.176,0.000,14.41,0.890062,14
14,Liam Lawson,Racing Bulls,0.000,0.000,0.003,0.102,0.145,0.000,15.26,0.879055,15
15,Gabriel Bortoleto,Audi,0.000,0.000,0.003,0.160,0.249,0.000,15.04,0.889754,16
16,Esteban Ocon,Haas,0.000,0.002,0.018,0.367,0.157,0.000,12.82,0.906542,17
17,Alex Albon,Williams,0.000,0.002,0.039,0.426,0.108,0.000,11.90,0.910344,18
18,Nico Hulkenberg,Audi,0.000,0.001,0.001,0.066,0.230,0.000,15.84,0.878397,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.410,0.000,19.55,0.764336,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.004,0.392,0.000,18.80,0.826077,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.045,0.205,0.000,16.37,0.866696,22

========== ROUND 6 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Charles Leclerc,Ferrari,0.305,0.708,0.914,0.962,0.038,0.305,3.28,1.041877,1
1,Kimi Antonelli,Mercedes,0.231,0.668,0.888,0.946,0.053,0.231,3.73,1.038356,2
2,George Russell,Mercedes,0.228,0.652,0.867,0.931,0.068,0.228,3.99,1.038681,3
3,Lewis Hamilton,Ferrari,0.160,0.540,0.859,0.967,0.031,0.160,3.89,1.028107,4
4,Oscar Piastri,McLaren,0.046,0.239,0.636,0.896,0.095,0.046,6.11,1.008027,5
5,Lando Norris,McLaren,0.018,0.116,0.409,0.884,0.083,0.018,7.10,0.991430,6
6,Max Verstappen,Red Bull Racing,0.008,0.052,0.198,0.766,0.176,0.008,9.26,0.978558,7
7,Pierre Gasly,Alpine,0.002,0.011,0.074,0.673,0.140,0.002,10.25,0.957083,8
8,Oliver Bearman,Haas,0.002,0.008,0.057,0.652,0.125,0.002,10.34,0.952536,9
9,Esteban Ocon,Haas,0.000,0.001,0.027,0.447,0.154,0.000,11.98,0.935955,10
10,Sergio Perez,Cadillac,0.000,0.000,0.002,0.151,0.196,0.000,14.52,0.907861,11
11,Franco Colapinto,Alpine,0.000,0.000,0.011,0.340,0.115,0.000,12.40,0.925708,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.000,0.051,0.180,0.000,15.77,0.887498,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.018,0.162,0.000,16.84,0.867865,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.001,0.137,0.249,0.000,15.03,0.905793,15
15,Carlos Sainz,Williams,0.000,0.004,0.041,0.587,0.107,0.000,10.73,0.945967,16
16,Alex Albon,Williams,0.000,0.001,0.014,0.367,0.121,0.000,12.46,0.926668,17
17,Isak Hadjar,Red Bull Racing,0.000,0.000,0.002,0.149,0.175,0.000,14.47,0.906658,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.057,0.240,0.000,15.88,0.890319,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.399,0.000,19.49,0.772988,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.000,0.404,0.000,18.84,0.835606,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.019,0.202,0.000,16.65,0.875273,22

========== ROUND 7 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.287,0.678,0.847,0.931,0.067,0.287,3.90,1.021061,1
1,George Russell,Mercedes,0.252,0.632,0.837,0.944,0.056,0.252,3.92,1.016701,2
2,Charles Leclerc,Ferrari,0.213,0.591,0.850,0.962,0.038,0.213,3.81,1.013683,3
3,Lewis Hamilton,Ferrari,0.114,0.402,0.759,0.961,0.037,0.114,4.57,1.002379,4
4,Oscar Piastri,McLaren,0.080,0.354,0.702,0.933,0.066,0.080,5.30,0.998991,5
5,Lando Norris,McLaren,0.041,0.216,0.530,0.918,0.075,0.041,6.21,0.987872,6
6,Max Verstappen,Red Bull Racing,0.013,0.104,0.321,0.838,0.139,0.013,8.07,0.975981,7
7,Esteban Ocon,Haas,0.000,0.002,0.007,0.349,0.139,0.000,12.57,0.918526,8
8,Sergio Perez,Cadillac,0.000,0.000,0.000,0.050,0.183,0.000,16.07,0.883061,9
9,Franco Colapinto,Alpine,0.000,0.001,0.002,0.141,0.125,0.000,14.32,0.898748,10
10,Pierre Gasly,Alpine,0.000,0.006,0.051,0.646,0.129,0.000,10.60,0.940050,11
11,Arvid Lindblad,Racing Bulls,0.000,0.000,0.001,0.105,0.160,0.000,15.02,0.893744,12
12,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.079,0.174,0.000,15.23,0.892762,13
13,Oliver Bearman,Haas,0.000,0.001,0.018,0.481,0.129,0.000,11.77,0.926622,14
14,Gabriel Bortoleto,Audi,0.000,0.001,0.001,0.131,0.207,0.000,15.02,0.897568,15
15,Carlos Sainz,Williams,0.000,0.009,0.051,0.682,0.113,0.000,10.27,0.941187,16
16,Alex Albon,Williams,0.000,0.003,0.018,0.461,0.111,0.000,11.70,0.925676,17
17,Isak Hadjar,Red Bull Racing,0.000,0.000,0.005,0.298,0.137,0.000,13.00,0.914237,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.067,0.220,0.000,15.99,0.886185,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.373,0.000,19.65,0.768461,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.000,0.388,0.000,19.09,0.831824,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.023,0.200,0.000,16.92,0.873231,22

========== ROUND 8 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.265,0.644,0.847,0.944,0.056,0.265,3.88,1.011957,1
1,George Russell,Mercedes,0.222,0.561,0.819,0.942,0.058,0.222,4.20,1.007475,2
2,Lewis Hamilton,Ferrari,0.210,0.581,0.835,0.976,0.023,0.210,3.70,1.005258,3
3,Charles Leclerc,Ferrari,0.162,0.511,0.791,0.962,0.034,0.162,4.12,1.001781,4
4,Oscar Piastri,McLaren,0.062,0.263,0.524,0.891,0.098,0.062,6.46,0.983919,5
5,Lando Norris,McLaren,0.041,0.231,0.523,0.884,0.091,0.041,6.57,0.980996,6
6,Max Verstappen,Red Bull Racing,0.036,0.176,0.429,0.825,0.159,0.036,7.82,0.977973,7
7,Carlos Sainz,Williams,0.002,0.018,0.096,0.695,0.103,0.002,9.82,0.939319,8
8,Oliver Bearman,Haas,0.000,0.003,0.035,0.500,0.139,0.000,11.63,0.922961,9
9,Sergio Perez,Cadillac,0.000,0.000,0.002,0.096,0.215,0.000,15.59,0.881774,10
10,Franco Colapinto,Alpine,0.000,0.000,0.002,0.165,0.115,0.000,14.07,0.892967,11
11,Pierre Gasly,Alpine,0.000,0.006,0.045,0.514,0.138,0.000,11.46,0.924711,12
12,Arvid Lindblad,Racing Bulls,0.000,0.001,0.001,0.165,0.166,0.000,14.53,0.890731,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.002,0.094,0.166,0.000,15.30,0.881365,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.003,0.116,0.236,0.000,15.42,0.888747,15
15,Esteban Ocon,Haas,0.000,0.002,0.009,0.319,0.164,0.000,13.07,0.908961,16
16,Alex Albon,Williams,0.000,0.001,0.013,0.365,0.102,0.000,12.38,0.909852,17
17,Isak Hadjar,Red Bull Racing,0.000,0.002,0.023,0.422,0.182,0.000,12.47,0.918514,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.001,0.083,0.251,0.000,15.96,0.880852,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.402,0.000,19.48,0.769052,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.003,0.406,0.000,18.71,0.837140,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.039,0.173,0.000,16.33,0.867423,22

========== ROUND 9 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.310,0.681,0.879,0.950,0.049,0.310,3.56,1.021877,1
1,Kimi Antonelli,Mercedes,0.244,0.636,0.876,0.951,0.048,0.244,3.75,1.017826,2
2,Lewis Hamilton,Ferrari,0.190,0.563,0.838,0.972,0.026,0.190,3.77,1.011589,3
3,Charles Leclerc,Ferrari,0.151,0.534,0.818,0.969,0.030,0.151,4.01,1.009290,4
4,Lando Norris,McLaren,0.057,0.257,0.557,0.893,0.093,0.057,6.35,0.991567,5
5,Oscar Piastri,McLaren,0.033,0.220,0.552,0.899,0.089,0.033,6.39,0.989350,6
6,Max Verstappen,Red Bull Racing,0.012,0.085,0.310,0.806,0.168,0.012,8.64,0.975312,7
7,Carlos Sainz,Williams,0.002,0.009,0.050,0.658,0.099,0.002,10.21,0.942595,8
8,Alex Albon,Williams,0.001,0.007,0.039,0.589,0.108,0.001,10.88,0.935818,9
9,Oliver Bearman,Haas,0.000,0.000,0.014,0.401,0.131,0.000,12.20,0.924189,10
10,Sergio Perez,Cadillac,0.000,0.000,0.000,0.087,0.175,0.000,15.28,0.893543,11
11,Franco Colapinto,Alpine,0.000,0.000,0.003,0.240,0.127,0.000,13.41,0.910761,12
12,Pierre Gasly,Alpine,0.000,0.004,0.033,0.541,0.145,0.000,11.31,0.937279,13
13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.000,0.065,0.172,0.000,15.68,0.888080,14
14,Liam Lawson,Racing Bulls,0.000,0.000,0.002,0.043,0.180,0.000,16.16,0.882638,15
15,Gabriel Bortoleto,Audi,0.000,0.000,0.001,0.110,0.223,0.000,15.29,0.897117,16
16,Esteban Ocon,Haas,0.000,0.000,0.013,0.373,0.149,0.000,12.37,0.924230,17
17,Isak Hadjar,Red Bull Racing,0.000,0.004,0.015,0.364,0.154,0.000,12.62,0.922766,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.050,0.226,0.000,16.20,0.884796,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.382,0.000,19.61,0.771397,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.000,0.356,0.000,18.91,0.834286,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.039,0.180,0.000,16.40,0.878385,22

========== ROUND 10 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.283,0.663,0.862,0.938,0.061,0.283,3.82,1.012883,1
1,George Russell,Mercedes,0.264,0.631,0.841,0.940,0.060,0.264,3.95,1.010677,2
2,Charles Leclerc,Ferrari,0.182,0.578,0.830,0.970,0.028,0.182,3.79,1.004369,3
3,Lewis Hamilton,Ferrari,0.135,0.449,0.764,0.968,0.031,0.135,4.41,0.996755,4
4,Oscar Piastri,McLaren,0.072,0.308,0.626,0.896,0.087,0.072,5.96,0.987645,5
5,Lando Norris,McLaren,0.044,0.226,0.515,0.892,0.087,0.044,6.45,0.981942,6
6,Max Verstappen,Red Bull Racing,0.017,0.113,0.369,0.795,0.187,0.017,8.50,0.974761,7
7,Oliver Bearman,Haas,0.001,0.005,0.038,0.487,0.146,0.001,11.78,0.926890,8
8,Carlos Sainz,Williams,0.001,0.017,0.066,0.665,0.117,0.001,10.14,0.941121,9
9,Esteban Ocon,Haas,0.001,0.001,0.014,0.313,0.147,0.001,13.00,0.913309,10
10,Sergio Perez,Cadillac,0.000,0.000,0.001,0.049,0.183,0.000,16.05,0.881531,11
11,Franco Colapinto,Alpine,0.000,0.000,0.005,0.166,0.130,0.000,14.02,0.901570,12
12,Pierre Gasly,Alpine,0.000,0.002,0.025,0.541,0.110,0.000,11.21,0.928667,13
13,Arvid Lindblad,Racing Bulls,0.000,0.000,0.001,0.170,0.172,0.000,14.37,0.901280,14
14,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.083,0.161,0.000,15.29,0.889972,15
15,Gabriel Bortoleto,Audi,0.000,0.001,0.003,0.145,0.235,0.000,15.00,0.899413,16
16,Alex Albon,Williams,0.000,0.001,0.015,0.367,0.129,0.000,12.68,0.915500,17
17,Isak Hadjar,Red Bull Racing,0.000,0.005,0.024,0.500,0.158,0.000,11.71,0.928707,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.001,0.087,0.253,0.000,15.86,0.889794,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.399,0.000,19.55,0.769567,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.001,0.401,0.000,18.91,0.831910,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.027,0.195,0.000,16.55,0.873339,22

========== ROUND 11 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.321,0.706,0.896,0.950,0.049,0.321,3.42,1.038311,1
1,Charles Leclerc,Ferrari,0.263,0.683,0.896,0.960,0.039,0.263,3.46,1.035765,2
2,Kimi Antonelli,Mercedes,0.234,0.661,0.870,0.938,0.061,0.234,3.91,1.034485,3
3,Oscar Piastri,McLaren,0.078,0.334,0.708,0.903,0.096,0.078,5.66,1.016068,4
4,Lewis Hamilton,Ferrari,0.072,0.342,0.698,0.952,0.045,0.072,4.99,1.013119,5
5,Lando Norris,McLaren,0.025,0.198,0.552,0.897,0.096,0.025,6.49,1.002657,6
6,Max Verstappen,Red Bull Racing,0.005,0.050,0.215,0.802,0.152,0.005,8.88,0.978936,7
7,Pierre Gasly,Alpine,0.001,0.010,0.056,0.663,0.145,0.001,10.47,0.955810,8
8,Carlos Sainz,Williams,0.001,0.012,0.055,0.700,0.133,0.001,10.15,0.957829,9
9,Oliver Bearman,Haas,0.000,0.002,0.016,0.483,0.128,0.000,11.62,0.939325,10
10,Sergio Perez,Cadillac,0.000,0.000,0.002,0.073,0.169,0.000,15.18,0.900280,11
11,Franco Colapinto,Alpine,0.000,0.000,0.002,0.232,0.147,0.000,13.36,0.921708,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.000,0.029,0.152,0.000,16.18,0.884607,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.013,0.158,0.000,16.90,0.874095,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.001,0.166,0.227,0.000,14.56,0.914116,15
15,Esteban Ocon,Haas,0.000,0.000,0.007,0.344,0.132,0.000,12.54,0.929229,16
16,Alex Albon,Williams,0.000,0.000,0.013,0.393,0.120,0.000,12.13,0.933366,17
17,Isak Hadjar,Red Bull Racing,0.000,0.002,0.013,0.421,0.159,0.000,12.28,0.935799,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.056,0.233,0.000,15.85,0.896770,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.396,0.000,19.59,0.777658,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.000,0.383,0.000,18.90,0.842562,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.025,0.176,0.000,16.48,0.884108,22

========== ROUND 12 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Lewis Hamilton,Ferrari,0.275,0.692,0.895,0.973,0.026,0.275,3.25,1.050641,1
1,George Russell,Mercedes,0.248,0.653,0.851,0.934,0.066,0.248,4.02,1.049492,2
2,Kimi Antonelli,Mercedes,0.212,0.588,0.844,0.937,0.062,0.212,4.14,1.045342,3
3,Charles Leclerc,Ferrari,0.181,0.560,0.846,0.961,0.036,0.181,3.90,1.040991,4
4,Oscar Piastri,McLaren,0.037,0.188,0.522,0.901,0.086,0.037,6.53,1.011363,5
5,Max Verstappen,Red Bull Racing,0.023,0.148,0.426,0.826,0.161,0.023,7.87,1.007540,6
6,Lando Norris,McLaren,0.021,0.143,0.403,0.877,0.093,0.021,7.17,1.002102,7
7,Carlos Sainz,Williams,0.002,0.012,0.081,0.706,0.110,0.002,9.89,0.964197,8
8,Oliver Bearman,Haas,0.001,0.006,0.052,0.625,0.134,0.001,10.67,0.956881,9
9,Sergio Perez,Cadillac,0.000,0.000,0.000,0.046,0.174,0.000,15.90,0.889294,10
10,Franco Colapinto,Alpine,0.000,0.001,0.001,0.117,0.127,0.000,14.55,0.904790,11
11,Pierre Gasly,Alpine,0.000,0.006,0.048,0.601,0.115,0.000,10.72,0.953004,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.000,0.063,0.146,0.000,15.59,0.891704,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.051,0.170,0.000,16.06,0.885837,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.002,0.199,0.240,0.000,14.52,0.917254,15
15,Esteban Ocon,Haas,0.000,0.003,0.016,0.424,0.136,0.000,12.14,0.937618,16
16,Alex Albon,Williams,0.000,0.000,0.008,0.391,0.106,0.000,12.12,0.932533,17
17,Isak Hadjar,Red Bull Racing,0.000,0.000,0.005,0.267,0.151,0.000,13.24,0.924260,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.057,0.236,0.000,16.09,0.891451,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.397,0.000,19.66,0.777739,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.002,0.365,0.000,18.58,0.850874,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.042,0.177,0.000,16.40,0.880010,22

========== ROUND 13 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.281,0.632,0.836,0.939,0.061,0.281,3.97,1.015077,1
1,Kimi Antonelli,Mercedes,0.280,0.639,0.851,0.928,0.072,0.280,4.04,1.016467,2
2,Charles Leclerc,Ferrari,0.181,0.589,0.844,0.975,0.025,0.181,3.72,1.009520,3
3,Lewis Hamilton,Ferrari,0.141,0.451,0.766,0.966,0.028,0.141,4.28,1.002167,4
4,Lando Norris,McLaren,0.057,0.268,0.597,0.916,0.076,0.057,5.96,0.991206,5
5,Oscar Piastri,McLaren,0.036,0.214,0.497,0.894,0.088,0.036,6.51,0.987207,6
6,Max Verstappen,Red Bull Racing,0.021,0.175,0.415,0.833,0.157,0.021,7.79,0.984132,7
7,Carlos Sainz,Williams,0.002,0.012,0.061,0.648,0.119,0.002,10.53,0.944019,8
8,Pierre Gasly,Alpine,0.001,0.007,0.046,0.565,0.118,0.001,10.87,0.939440,9
9,Oliver Bearman,Haas,0.000,0.003,0.021,0.381,0.147,0.000,12.45,0.926091,10
10,Sergio Perez,Cadillac,0.000,0.000,0.000,0.036,0.180,0.000,16.35,0.883846,11
11,Franco Colapinto,Alpine,0.000,0.001,0.004,0.198,0.136,0.000,13.93,0.909142,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.004,0.181,0.185,0.000,14.25,0.909855,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.003,0.117,0.171,0.000,14.90,0.901647,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.001,0.089,0.222,0.000,15.42,0.898085,15
15,Esteban Ocon,Haas,0.000,0.002,0.013,0.369,0.134,0.000,12.48,0.924032,16
16,Alex Albon,Williams,0.000,0.004,0.017,0.450,0.111,0.000,11.71,0.929905,17
17,Isak Hadjar,Red Bull Racing,0.000,0.002,0.023,0.447,0.153,0.000,11.99,0.931610,18
18,Nico Hulkenberg,Audi,0.000,0.001,0.001,0.047,0.219,0.000,16.25,0.887570,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.394,0.000,19.58,0.770538,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.001,0.399,0.000,19.14,0.831544,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.020,0.189,0.000,16.88,0.875924,22

========== ROUND 14 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.286,0.683,0.873,0.945,0.054,0.286,3.65,1.028432,1
1,George Russell,Mercedes,0.243,0.612,0.840,0.927,0.071,0.243,4.25,1.025239,2
2,Charles Leclerc,Ferrari,0.223,0.591,0.858,0.971,0.028,0.223,3.62,1.021475,3
3,Lewis Hamilton,Ferrari,0.149,0.509,0.795,0.960,0.037,0.149,4.21,1.014211,4
4,Lando Norris,McLaren,0.050,0.257,0.596,0.914,0.079,0.050,6.00,0.998265,5
5,Oscar Piastri,McLaren,0.029,0.197,0.494,0.876,0.108,0.029,6.82,0.993648,6
6,Max Verstappen,Red Bull Racing,0.017,0.117,0.324,0.809,0.156,0.017,8.37,0.981978,7
7,Oliver Bearman,Haas,0.002,0.010,0.058,0.567,0.142,0.002,11.10,0.943470,8
8,Pierre Gasly,Alpine,0.001,0.009,0.047,0.551,0.112,0.001,11.04,0.940352,9
9,Esteban Ocon,Haas,0.000,0.000,0.009,0.364,0.150,0.000,12.74,0.925714,10
10,Sergio Perez,Cadillac,0.000,0.000,0.000,0.059,0.166,0.000,15.92,0.890749,11
11,Franco Colapinto,Alpine,0.000,0.000,0.007,0.268,0.123,0.000,13.35,0.916044,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.002,0.089,0.162,0.000,15.33,0.897155,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.002,0.085,0.164,0.000,15.20,0.898724,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.001,0.124,0.214,0.000,15.09,0.903982,15
15,Carlos Sainz,Williams,0.000,0.012,0.074,0.654,0.131,0.000,10.31,0.950800,16
16,Alex Albon,Williams,0.000,0.002,0.014,0.371,0.103,0.000,12.35,0.924869,17
17,Isak Hadjar,Red Bull Racing,0.000,0.001,0.005,0.346,0.177,0.000,12.95,0.925432,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.001,0.101,0.227,0.000,15.56,0.900047,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.385,0.000,19.57,0.776503,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.000,0.416,0.000,19.03,0.839655,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.019,0.181,0.000,16.55,0.881142,22

========== ROUND 15 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.268,0.616,0.835,0.942,0.057,0.268,3.96,1.014238,1
1,Kimi Antonelli,Mercedes,0.259,0.637,0.847,0.942,0.055,0.259,3.90,1.014146,2
2,Charles Leclerc,Ferrari,0.186,0.576,0.823,0.961,0.035,0.186,3.97,1.007863,3
3,Lewis Hamilton,Ferrari,0.127,0.424,0.716,0.947,0.042,0.127,4.75,0.999025,4
4,Oscar Piastri,McLaren,0.066,0.268,0.560,0.876,0.106,0.066,6.53,0.989295,5
5,Lando Norris,McLaren,0.051,0.247,0.523,0.897,0.081,0.051,6.40,0.985694,6
6,Max Verstappen,Red Bull Racing,0.031,0.162,0.399,0.816,0.147,0.031,7.88,0.980015,7
7,Isak Hadjar,Red Bull Racing,0.005,0.012,0.044,0.492,0.145,0.005,11.62,0.934768,8
8,Carlos Sainz,Williams,0.004,0.027,0.103,0.675,0.104,0.004,9.97,0.947059,9
9,Pierre Gasly,Alpine,0.001,0.011,0.048,0.506,0.127,0.001,11.53,0.932601,10
10,Esteban Ocon,Haas,0.001,0.003,0.015,0.293,0.158,0.001,13.05,0.919533,11
11,Oliver Bearman,Haas,0.001,0.008,0.034,0.396,0.145,0.001,12.32,0.926435,12
12,Liam Lawson,Racing Bulls,0.000,0.001,0.002,0.120,0.180,0.000,14.94,0.900085,13
13,Sergio Perez,Cadillac,0.000,0.000,0.003,0.069,0.180,0.000,15.68,0.890779,14
14,Franco Colapinto,Alpine,0.000,0.000,0.004,0.205,0.123,0.000,13.83,0.908361,15
15,Arvid Lindblad,Racing Bulls,0.000,0.001,0.004,0.189,0.168,0.000,14.31,0.906145,16
16,Gabriel Bortoleto,Audi,0.000,0.001,0.004,0.120,0.211,0.000,15.07,0.900260,17
17,Alex Albon,Williams,0.000,0.006,0.034,0.448,0.104,0.000,11.79,0.927283,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.001,0.067,0.244,0.000,16.25,0.888863,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.398,0.000,19.57,0.774579,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.002,0.389,0.000,18.95,0.835654,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.001,0.037,0.188,0.000,16.75,0.875826,22

========== ROUND 16 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.255,0.619,0.831,0.932,0.067,0.255,4.12,1.051355,1
1,Lewis Hamilton,Ferrari,0.238,0.613,0.873,0.964,0.035,0.238,3.63,1.048852,2
2,George Russell,Mercedes,0.201,0.559,0.830,0.941,0.059,0.201,4.24,1.045884,3
3,Charles Leclerc,Ferrari,0.180,0.579,0.839,0.958,0.041,0.180,3.90,1.045786,4
4,Lando Norris,McLaren,0.063,0.312,0.640,0.900,0.096,0.063,5.94,1.024021,5
5,Oscar Piastri,McLaren,0.048,0.214,0.535,0.888,0.101,0.048,6.54,1.015224,6
6,Max Verstappen,Red Bull Racing,0.010,0.070,0.244,0.790,0.173,0.010,8.94,0.994371,7
7,Carlos Sainz,Williams,0.002,0.012,0.074,0.656,0.126,0.002,10.26,0.960870,8
8,Oliver Bearman,Haas,0.001,0.007,0.035,0.554,0.162,0.001,11.34,0.951482,9
9,Franco Colapinto,Alpine,0.001,0.001,0.008,0.317,0.124,0.001,12.79,0.927886,10
10,Pierre Gasly,Alpine,0.001,0.007,0.035,0.515,0.147,0.001,11.51,0.946913,11
11,Sergio Perez,Cadillac,0.000,0.000,0.001,0.111,0.185,0.000,15.11,0.902626,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.002,0.090,0.167,0.000,15.30,0.896828,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.001,0.028,0.189,0.000,16.73,0.874336,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.003,0.115,0.245,0.000,15.40,0.903216,15
15,Esteban Ocon,Haas,0.000,0.006,0.029,0.493,0.156,0.000,11.74,0.944477,16
16,Alex Albon,Williams,0.000,0.001,0.006,0.271,0.113,0.000,13.09,0.922233,17
17,Isak Hadjar,Red Bull Racing,0.000,0.000,0.010,0.293,0.197,0.000,13.48,0.925492,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.004,0.119,0.236,0.000,15.29,0.903812,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.380,0.000,19.29,0.786380,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.005,0.396,0.000,18.28,0.860156,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.060,0.223,0.000,16.07,0.890028,22

========== ROUND 17 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.252,0.642,0.866,0.940,0.059,0.252,3.89,1.029013,1
1,Kimi Antonelli,Mercedes,0.246,0.661,0.864,0.933,0.065,0.246,3.94,1.030578,2
2,Charles Leclerc,Ferrari,0.220,0.583,0.876,0.978,0.021,0.220,3.51,1.024794,3
3,Lewis Hamilton,Ferrari,0.197,0.607,0.855,0.973,0.026,0.197,3.63,1.024147,4
4,Lando Norris,McLaren,0.036,0.214,0.527,0.883,0.101,0.036,6.58,0.999283,5
5,Oscar Piastri,McLaren,0.031,0.175,0.480,0.903,0.082,0.031,6.63,0.993458,6
6,Max Verstappen,Red Bull Racing,0.017,0.100,0.365,0.827,0.147,0.017,8.09,0.987441,7
7,Carlos Sainz,Williams,0.001,0.008,0.064,0.684,0.126,0.001,10.24,0.954688,8
8,Oliver Bearman,Haas,0.000,0.004,0.036,0.541,0.137,0.000,11.23,0.943955,9
9,Sergio Perez,Cadillac,0.000,0.000,0.000,0.050,0.195,0.000,16.11,0.891588,10
10,Franco Colapinto,Alpine,0.000,0.000,0.001,0.174,0.132,0.000,14.07,0.912465,11
11,Pierre Gasly,Alpine,0.000,0.002,0.018,0.507,0.116,0.000,11.41,0.940445,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.002,0.069,0.182,0.000,15.62,0.898644,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.000,0.063,0.141,0.000,15.75,0.893668,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.002,0.178,0.243,0.000,14.66,0.915999,15
15,Esteban Ocon,Haas,0.000,0.003,0.020,0.394,0.148,0.000,12.28,0.933960,16
16,Alex Albon,Williams,0.000,0.001,0.008,0.356,0.107,0.000,12.33,0.929680,17
17,Isak Hadjar,Red Bull Racing,0.000,0.000,0.016,0.402,0.153,0.000,12.52,0.931411,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.113,0.213,0.000,15.31,0.903858,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.388,0.000,19.52,0.780807,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.000,0.400,0.000,19.04,0.842205,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.032,0.210,0.000,16.63,0.885327,22

========== ROUND 18 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.265,0.670,0.856,0.939,0.060,0.265,3.84,1.033503,1
1,George Russell,Mercedes,0.250,0.593,0.839,0.940,0.058,0.250,4.07,1.030272,2
2,Charles Leclerc,Ferrari,0.182,0.547,0.831,0.975,0.024,0.182,3.84,1.023652,3
3,Lewis Hamilton,Ferrari,0.166,0.526,0.804,0.965,0.030,0.166,4.05,1.021670,4
4,Oscar Piastri,McLaren,0.063,0.259,0.561,0.895,0.099,0.063,6.30,1.004902,5
5,Lando Norris,McLaren,0.037,0.197,0.489,0.880,0.102,0.037,6.78,0.998729,6
6,Max Verstappen,Red Bull Racing,0.033,0.176,0.406,0.800,0.182,0.033,8.17,0.996935,7
7,Carlos Sainz,Williams,0.002,0.015,0.095,0.656,0.124,0.002,10.16,0.955991,8
8,Oliver Bearman,Haas,0.001,0.003,0.023,0.505,0.144,0.001,11.70,0.939483,9
9,Isak Hadjar,Red Bull Racing,0.001,0.005,0.026,0.438,0.159,0.001,12.06,0.936929,10
10,Sergio Perez,Cadillac,0.000,0.000,0.000,0.070,0.178,0.000,15.81,0.889137,11
11,Franco Colapinto,Alpine,0.000,0.000,0.007,0.201,0.119,0.000,13.77,0.912061,12
12,Pierre Gasly,Alpine,0.000,0.004,0.038,0.555,0.135,0.000,11.24,0.942216,13
13,Arvid Lindblad,Racing Bulls,0.000,0.001,0.003,0.173,0.176,0.000,14.42,0.908945,14
14,Liam Lawson,Racing Bulls,0.000,0.000,0.002,0.121,0.171,0.000,14.97,0.902010,15
15,Gabriel Bortoleto,Audi,0.000,0.000,0.003,0.134,0.245,0.000,15.34,0.904107,16
16,Esteban Ocon,Haas,0.000,0.001,0.003,0.250,0.146,0.000,13.50,0.917177,17
17,Alex Albon,Williams,0.000,0.003,0.012,0.372,0.126,0.000,12.35,0.929332,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.002,0.094,0.257,0.000,15.92,0.895774,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.389,0.000,19.45,0.778666,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.005,0.422,0.000,18.73,0.849150,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.032,0.193,0.000,16.54,0.879935,22

========== ROUND 19 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.280,0.682,0.885,0.941,0.059,0.280,3.71,1.032793,1
1,Charles Leclerc,Ferrari,0.225,0.631,0.861,0.961,0.039,0.225,3.69,1.027956,2
2,George Russell,Mercedes,0.217,0.641,0.857,0.936,0.061,0.217,3.99,1.028978,3
3,Lewis Hamilton,Ferrari,0.194,0.531,0.823,0.956,0.041,0.194,4.09,1.021987,4
4,Oscar Piastri,McLaren,0.034,0.206,0.551,0.884,0.102,0.034,6.62,0.998640,5
5,Lando Norris,McLaren,0.033,0.205,0.533,0.890,0.096,0.033,6.50,0.999055,6
6,Max Verstappen,Red Bull Racing,0.013,0.077,0.276,0.795,0.155,0.013,8.71,0.980589,7
7,Pierre Gasly,Alpine,0.002,0.012,0.054,0.562,0.133,0.002,10.98,0.947090,8
8,Esteban Ocon,Haas,0.001,0.005,0.023,0.423,0.119,0.001,11.98,0.934702,9
9,Oliver Bearman,Haas,0.001,0.002,0.045,0.501,0.163,0.001,11.63,0.943444,10
10,Sergio Perez,Cadillac,0.000,0.001,0.003,0.078,0.171,0.000,15.36,0.902242,11
11,Franco Colapinto,Alpine,0.000,0.001,0.007,0.302,0.130,0.000,13.04,0.924343,12
12,Arvid Lindblad,Racing Bulls,0.000,0.000,0.003,0.121,0.197,0.000,15.19,0.906171,13
13,Liam Lawson,Racing Bulls,0.000,0.000,0.001,0.088,0.175,0.000,15.49,0.899144,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.002,0.171,0.249,0.000,15.13,0.911217,15
15,Carlos Sainz,Williams,0.000,0.005,0.051,0.549,0.123,0.000,11.00,0.944989,16
16,Alex Albon,Williams,0.000,0.001,0.015,0.427,0.105,0.000,11.94,0.932944,17
17,Isak Hadjar,Red Bull Racing,0.000,0.000,0.009,0.304,0.170,0.000,13.17,0.927011,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.069,0.233,0.000,15.99,0.897310,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.390,0.000,19.53,0.783424,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.000,0.383,0.000,18.89,0.845413,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.001,0.042,0.182,0.000,16.37,0.887755,22

========== ROUND 20 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,Kimi Antonelli,Mercedes,0.294,0.668,0.840,0.937,0.060,0.294,3.85,1.022288,1
1,George Russell,Mercedes,0.259,0.607,0.829,0.928,0.072,0.259,4.24,1.019760,2
2,Charles Leclerc,Ferrari,0.180,0.568,0.819,0.965,0.030,0.180,3.94,1.013521,3
3,Lewis Hamilton,Ferrari,0.118,0.446,0.742,0.958,0.032,0.118,4.52,1.005544,4
4,Oscar Piastri,McLaren,0.056,0.263,0.562,0.892,0.088,0.056,6.26,0.994345,5
5,Max Verstappen,Red Bull Racing,0.044,0.196,0.464,0.828,0.146,0.044,7.51,0.991231,6
6,Lando Norris,McLaren,0.041,0.209,0.482,0.891,0.086,0.041,6.71,0.988553,7
7,Isak Hadjar,Red Bull Racing,0.004,0.013,0.057,0.550,0.165,0.004,11.32,0.945898,8
8,Carlos Sainz,Williams,0.002,0.017,0.078,0.659,0.093,0.002,10.10,0.950968,9
9,Liam Lawson,Racing Bulls,0.001,0.001,0.003,0.117,0.149,0.001,14.81,0.906557,10
10,Alex Albon,Williams,0.001,0.002,0.019,0.377,0.101,0.001,12.30,0.928763,11
11,Sergio Perez,Cadillac,0.000,0.000,0.002,0.050,0.177,0.000,16.03,0.893900,12
12,Franco Colapinto,Alpine,0.000,0.001,0.002,0.184,0.127,0.000,14.00,0.914272,13
13,Pierre Gasly,Alpine,0.000,0.008,0.055,0.533,0.113,0.000,11.17,0.941412,14
14,Arvid Lindblad,Racing Bulls,0.000,0.000,0.008,0.199,0.179,0.000,14.17,0.916759,15
15,Gabriel Bortoleto,Audi,0.000,0.000,0.003,0.103,0.237,0.000,15.58,0.904218,16
16,Oliver Bearman,Haas,0.000,0.001,0.020,0.406,0.116,0.000,12.08,0.932814,17
17,Esteban Ocon,Haas,0.000,0.000,0.012,0.312,0.143,0.000,13.05,0.925192,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.003,0.079,0.224,0.000,15.88,0.899394,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.370,0.000,19.63,0.781325,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.001,0.377,0.000,19.11,0.838504,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.031,0.171,0.000,16.72,0.881552,22

========== ROUND 21 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.288,0.716,0.879,0.930,0.070,0.288,3.82,1.050917,1
1,Kimi Antonelli,Mercedes,0.265,0.664,0.879,0.926,0.074,0.265,3.95,1.049544,2
2,Charles Leclerc,Ferrari,0.219,0.624,0.881,0.961,0.039,0.219,3.66,1.044354,3
3,Lewis Hamilton,Ferrari,0.169,0.535,0.837,0.965,0.034,0.169,4.02,1.037697,4
4,Oscar Piastri,McLaren,0.033,0.192,0.556,0.897,0.098,0.033,6.41,1.016415,5
5,Max Verstappen,Red Bull Racing,0.016,0.125,0.396,0.825,0.167,0.016,8.02,1.007798,6
6,Lando Norris,McLaren,0.010,0.135,0.452,0.904,0.091,0.010,6.79,1.009272,7
7,Esteban Ocon,Haas,0.000,0.000,0.004,0.277,0.148,0.000,13.18,0.936041,8
8,Sergio Perez,Cadillac,0.000,0.000,0.001,0.034,0.180,0.000,16.25,0.900865,9
9,Franco Colapinto,Alpine,0.000,0.000,0.002,0.220,0.104,0.000,13.38,0.928990,10
10,Pierre Gasly,Alpine,0.000,0.003,0.041,0.656,0.130,0.000,10.58,0.963280,11
11,Arvid Lindblad,Racing Bulls,0.000,0.000,0.000,0.089,0.144,0.000,15.08,0.912815,12
12,Liam Lawson,Racing Bulls,0.000,0.000,0.001,0.112,0.177,0.000,14.92,0.916715,13
13,Oliver Bearman,Haas,0.000,0.001,0.019,0.487,0.130,0.000,11.72,0.949850,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.001,0.134,0.227,0.000,14.97,0.921309,15
15,Carlos Sainz,Williams,0.000,0.003,0.026,0.590,0.104,0.000,10.81,0.956639,16
16,Alex Albon,Williams,0.000,0.001,0.014,0.458,0.095,0.000,11.57,0.948184,17
17,Isak Hadjar,Red Bull Racing,0.000,0.001,0.011,0.458,0.131,0.000,11.92,0.947267,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.061,0.251,0.000,16.12,0.906990,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.424,0.000,19.68,0.783698,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.001,0.365,0.000,19.00,0.848735,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.015,0.175,0.000,17.12,0.886094,22

========== ROUND 22 FULL PROBABILITIES ==========

,driver,team,win_prob,podium_prob,top5_prob,points_prob,dnf_prob,fl_prob,expected_pos,avg_pace,predicted_pos
0,George Russell,Mercedes,0.289,0.677,0.870,0.930,0.070,0.289,3.89,1.041124,1
1,Kimi Antonelli,Mercedes,0.277,0.689,0.872,0.950,0.050,0.277,3.61,1.039697,2
2,Lewis Hamilton,Ferrari,0.167,0.508,0.831,0.967,0.033,0.167,4.04,1.027905,3
3,Charles Leclerc,Ferrari,0.166,0.568,0.861,0.959,0.041,0.166,3.95,1.031328,4
4,Oscar Piastri,McLaren,0.053,0.232,0.581,0.925,0.069,0.053,5.89,1.010387,5
5,Lando Norris,McLaren,0.043,0.224,0.561,0.918,0.073,0.043,6.06,1.008034,6
6,Max Verstappen,Red Bull Racing,0.005,0.092,0.298,0.816,0.152,0.005,8.32,0.992782,7
7,Esteban Ocon,Haas,0.000,0.000,0.009,0.327,0.138,0.000,12.77,0.935630,8
8,Sergio Perez,Cadillac,0.000,0.000,0.000,0.040,0.163,0.000,16.00,0.900116,9
9,Franco Colapinto,Alpine,0.000,0.001,0.006,0.247,0.125,0.000,13.40,0.927801,10
10,Pierre Gasly,Alpine,0.000,0.000,0.018,0.549,0.119,0.000,11.26,0.950413,11
11,Arvid Lindblad,Racing Bulls,0.000,0.000,0.004,0.167,0.152,0.000,14.21,0.921399,12
12,Liam Lawson,Racing Bulls,0.000,0.000,0.001,0.049,0.171,0.000,16.09,0.899398,13
13,Oliver Bearman,Haas,0.000,0.001,0.029,0.512,0.134,0.000,11.53,0.948879,14
14,Gabriel Bortoleto,Audi,0.000,0.000,0.001,0.120,0.225,0.000,15.18,0.916451,15
15,Carlos Sainz,Williams,0.000,0.007,0.037,0.656,0.108,0.000,10.35,0.958386,16
16,Alex Albon,Williams,0.000,0.001,0.008,0.349,0.098,0.000,12.41,0.934697,17
17,Isak Hadjar,Red Bull Racing,0.000,0.000,0.013,0.445,0.151,0.000,12.20,0.943629,18
18,Nico Hulkenberg,Audi,0.000,0.000,0.000,0.055,0.225,0.000,16.13,0.903925,19
19,Lance Stroll,Aston Martin,0.000,0.000,0.000,0.000,0.383,0.000,19.67,0.787456,20
20,Fernando Alonso,Aston Martin,0.000,0.000,0.000,0.001,0.381,0.000,19.07,0.849987,21
21,Valtteri Bottas,Cadillac,0.000,0.000,0.000,0.018,0.176,0.000,16.96,0.888441,22

In [25]:
for rnd in sorted(all_quali["round"].unique()):
    print(f"\n========== ROUND {rnd} QUALIFYING ==========")
    display(
        all_quali[all_quali["round"] == rnd]
        .sort_values("quali_pos")
        .reset_index(drop=True)
    )

========== ROUND 1 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,George Russell,Mercedes,Mercedes,1.046562,1,Australia,1,1.0,10.904167,0.5
1,Kimi Antonelli,Mercedes,Mercedes,1.019292,2,Australia,1,1.0,10.904167,0.5
2,Lewis Hamilton,Ferrari,Ferrari,1.018664,3,Australia,1,1.0,10.904167,0.5
3,Charles Leclerc,Ferrari,Ferrari,1.009957,4,Australia,1,1.0,10.904167,0.5
4,Oscar Piastri,McLaren,Mercedes,0.999006,5,Australia,1,1.0,10.904167,0.5
5,Max Verstappen,Red Bull Racing,Red Bull Ford,0.979171,6,Australia,1,1.0,10.904167,0.5
6,Lando Norris,McLaren,Mercedes,0.965136,7,Australia,1,1.0,10.904167,0.5
7,Carlos Sainz,Williams,Mercedes,0.961960,8,Australia,1,1.0,10.904167,0.5
8,Oliver Bearman,Haas,Ferrari,0.951552,9,Australia,1,1.0,10.904167,0.5
9,Franco Colapinto,Alpine,Mercedes,0.949496,10,Australia,1,1.0,10.904167,0.5
10,Pierre Gasly,Alpine,Mercedes,0.947948,11,Australia,1,1.0,10.904167,0.5
11,Esteban Ocon,Haas,Ferrari,0.946714,12,Australia,1,1.0,10.904167,0.5
12,Nico Hulkenberg,Audi,Audi,0.940052,13,Australia,1,1.0,10.904167,0.5
13,Alex Albon,Williams,Mercedes,0.935031,14,Australia,1,1.0,10.904167,0.5
14,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.931850,15,Australia,1,1.0,10.904167,0.5
15,Gabriel Bortoleto,Audi,Audi,0.907921,16,Australia,1,1.0,10.904167,0.5
16,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.899160,17,Australia,1,1.0,10.904167,0.5
17,Sergio Perez,Cadillac,Ferrari,0.892968,18,Australia,1,1.0,10.904167,0.5
18,Liam Lawson,Racing Bulls,Red Bull Ford,0.886772,19,Australia,1,1.0,10.904167,0.5
19,Fernando Alonso,Aston Martin,Honda,0.872372,20,Australia,1,1.0,10.904167,0.5
20,Valtteri Bottas,Cadillac,Ferrari,0.871577,21,Australia,1,1.0,10.904167,0.5
21,Lance Stroll,Aston Martin,Honda,0.712062,22,Australia,1,1.0,10.904167,0.5

========== ROUND 2 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Charles Leclerc,Ferrari,Ferrari,1.029024,1,China,2,0.0,28.0375,0.45
1,Kimi Antonelli,Mercedes,Mercedes,1.011504,2,China,2,0.0,28.0375,0.45
2,George Russell,Mercedes,Mercedes,0.980958,3,China,2,0.0,28.0375,0.45
3,Oscar Piastri,McLaren,Mercedes,0.976709,4,China,2,0.0,28.0375,0.45
4,Esteban Ocon,Haas,Ferrari,0.942888,5,China,2,0.0,28.0375,0.45
5,Oliver Bearman,Haas,Ferrari,0.933808,6,China,2,0.0,28.0375,0.45
6,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.931482,7,China,2,0.0,28.0375,0.45
7,Lewis Hamilton,Ferrari,Ferrari,0.928202,8,China,2,0.0,28.0375,0.45
8,Franco Colapinto,Alpine,Mercedes,0.911905,9,China,2,0.0,28.0375,0.45
9,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.908409,10,China,2,0.0,28.0375,0.45
10,Lando Norris,McLaren,Mercedes,0.902447,11,China,2,0.0,28.0375,0.45
11,Max Verstappen,Red Bull Racing,Red Bull Ford,0.896355,12,China,2,0.0,28.0375,0.45
12,Carlos Sainz,Williams,Mercedes,0.893271,13,China,2,0.0,28.0375,0.45
13,Alex Albon,Williams,Mercedes,0.874234,14,China,2,0.0,28.0375,0.45
14,Sergio Perez,Cadillac,Ferrari,0.872434,15,China,2,0.0,28.0375,0.45
15,Valtteri Bottas,Cadillac,Ferrari,0.862611,16,China,2,0.0,28.0375,0.45
16,Pierre Gasly,Alpine,Mercedes,0.853559,17,China,2,0.0,28.0375,0.45
17,Nico Hulkenberg,Audi,Audi,0.835480,18,China,2,0.0,28.0375,0.45
18,Liam Lawson,Racing Bulls,Red Bull Ford,0.817845,19,China,2,0.0,28.0375,0.45
19,Gabriel Bortoleto,Audi,Audi,0.808903,20,China,2,0.0,28.0375,0.45
20,Fernando Alonso,Aston Martin,Honda,0.759978,21,China,2,0.0,28.0375,0.45
21,Lance Stroll,Aston Martin,Honda,0.715130,22,China,2,0.0,28.0375,0.45

========== ROUND 3 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Charles Leclerc,Ferrari,Ferrari,1.073588,1,Japan,3,1.0,24.425,0.55
1,Kimi Antonelli,Mercedes,Mercedes,1.055791,2,Japan,3,1.0,24.425,0.55
2,George Russell,Mercedes,Mercedes,1.021716,3,Japan,3,1.0,24.425,0.55
3,Oscar Piastri,McLaren,Mercedes,1.018514,4,Japan,3,1.0,24.425,0.55
4,Lando Norris,McLaren,Mercedes,0.996248,5,Japan,3,1.0,24.425,0.55
5,Carlos Sainz,Williams,Mercedes,0.970267,6,Japan,3,1.0,24.425,0.55
6,Gabriel Bortoleto,Audi,Audi,0.958533,7,Japan,3,1.0,24.425,0.55
7,Lewis Hamilton,Ferrari,Ferrari,0.955633,8,Japan,3,1.0,24.425,0.55
8,Max Verstappen,Red Bull Racing,Red Bull Ford,0.954484,9,Japan,3,1.0,24.425,0.55
9,Franco Colapinto,Alpine,Mercedes,0.948696,10,Japan,3,1.0,24.425,0.55
10,Esteban Ocon,Haas,Ferrari,0.936049,11,Japan,3,1.0,24.425,0.55
11,Alex Albon,Williams,Mercedes,0.932642,12,Japan,3,1.0,24.425,0.55
12,Oliver Bearman,Haas,Ferrari,0.924259,13,Japan,3,1.0,24.425,0.55
13,Nico Hulkenberg,Audi,Audi,0.917114,14,Japan,3,1.0,24.425,0.55
14,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.904057,15,Japan,3,1.0,24.425,0.55
15,Pierre Gasly,Alpine,Mercedes,0.903559,16,Japan,3,1.0,24.425,0.55
16,Liam Lawson,Racing Bulls,Red Bull Ford,0.898237,17,Japan,3,1.0,24.425,0.55
17,Sergio Perez,Cadillac,Ferrari,0.890660,18,Japan,3,1.0,24.425,0.55
18,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.885039,19,Japan,3,1.0,24.425,0.55
19,Valtteri Bottas,Cadillac,Ferrari,0.847605,20,Japan,3,1.0,24.425,0.55
20,Fernando Alonso,Aston Martin,Honda,0.801814,21,Japan,3,1.0,24.425,0.55
21,Lance Stroll,Aston Martin,Honda,0.794068,22,Japan,3,1.0,24.425,0.55

========== ROUND 4 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Kimi Antonelli,Mercedes,Mercedes,1.036798,1,Miami,4,1.0,26.570833,0.65
1,Charles Leclerc,Ferrari,Ferrari,1.028194,2,Miami,4,1.0,26.570833,0.65
2,Lewis Hamilton,Ferrari,Ferrari,1.018192,3,Miami,4,1.0,26.570833,0.65
3,Max Verstappen,Red Bull Racing,Red Bull Ford,1.013814,4,Miami,4,1.0,26.570833,0.65
4,Oscar Piastri,McLaren,Mercedes,1.007628,5,Miami,4,1.0,26.570833,0.65
5,George Russell,Mercedes,Mercedes,1.006816,6,Miami,4,1.0,26.570833,0.65
6,Lando Norris,McLaren,Mercedes,0.995485,7,Miami,4,1.0,26.570833,0.65
7,Carlos Sainz,Williams,Mercedes,0.977497,8,Miami,4,1.0,26.570833,0.65
8,Esteban Ocon,Haas,Ferrari,0.965041,9,Miami,4,1.0,26.570833,0.65
9,Pierre Gasly,Alpine,Mercedes,0.948042,10,Miami,4,1.0,26.570833,0.65
10,Alex Albon,Williams,Mercedes,0.946466,11,Miami,4,1.0,26.570833,0.65
11,Franco Colapinto,Alpine,Mercedes,0.939414,12,Miami,4,1.0,26.570833,0.65
12,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.929118,13,Miami,4,1.0,26.570833,0.65
13,Nico Hulkenberg,Audi,Audi,0.920692,14,Miami,4,1.0,26.570833,0.65
14,Sergio Perez,Cadillac,Ferrari,0.906526,15,Miami,4,1.0,26.570833,0.65
15,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.902100,16,Miami,4,1.0,26.570833,0.65
16,Gabriel Bortoleto,Audi,Audi,0.900918,17,Miami,4,1.0,26.570833,0.65
17,Oliver Bearman,Haas,Ferrari,0.900751,18,Miami,4,1.0,26.570833,0.65
18,Valtteri Bottas,Cadillac,Ferrari,0.891329,19,Miami,4,1.0,26.570833,0.65
19,Liam Lawson,Racing Bulls,Red Bull Ford,0.877577,20,Miami,4,1.0,26.570833,0.65
20,Lance Stroll,Aston Martin,Honda,0.812917,21,Miami,4,1.0,26.570833,0.65
21,Fernando Alonso,Aston Martin,Honda,0.781510,22,Miami,4,1.0,26.570833,0.65

========== ROUND 5 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Lewis Hamilton,Ferrari,Ferrari,0.972143,1,Canada,5,0.0,22.6375,0.55
1,Kimi Antonelli,Mercedes,Mercedes,0.970454,2,Canada,5,0.0,22.6375,0.55
2,Max Verstappen,Red Bull Racing,Red Bull Ford,0.964902,3,Canada,5,0.0,22.6375,0.55
3,Charles Leclerc,Ferrari,Ferrari,0.955010,4,Canada,5,0.0,22.6375,0.55
4,Lando Norris,McLaren,Mercedes,0.954377,5,Canada,5,0.0,22.6375,0.55
5,Carlos Sainz,Williams,Mercedes,0.945282,6,Canada,5,0.0,22.6375,0.55
6,George Russell,Mercedes,Mercedes,0.934396,7,Canada,5,0.0,22.6375,0.55
7,Oliver Bearman,Haas,Ferrari,0.932797,8,Canada,5,0.0,22.6375,0.55
8,Oscar Piastri,McLaren,Mercedes,0.918588,9,Canada,5,0.0,22.6375,0.55
9,Esteban Ocon,Haas,Ferrari,0.909838,10,Canada,5,0.0,22.6375,0.55
10,Alex Albon,Williams,Mercedes,0.906053,11,Canada,5,0.0,22.6375,0.55
11,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.902811,12,Canada,5,0.0,22.6375,0.55
12,Pierre Gasly,Alpine,Mercedes,0.891025,13,Canada,5,0.0,22.6375,0.55
13,Gabriel Bortoleto,Audi,Audi,0.881861,14,Canada,5,0.0,22.6375,0.55
14,Liam Lawson,Racing Bulls,Red Bull Ford,0.878143,15,Canada,5,0.0,22.6375,0.55
15,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.862690,16,Canada,5,0.0,22.6375,0.55
16,Franco Colapinto,Alpine,Mercedes,0.858718,17,Canada,5,0.0,22.6375,0.55
17,Nico Hulkenberg,Audi,Audi,0.847326,18,Canada,5,0.0,22.6375,0.55
18,Sergio Perez,Cadillac,Ferrari,0.845836,19,Canada,5,0.0,22.6375,0.55
19,Valtteri Bottas,Cadillac,Ferrari,0.828749,20,Canada,5,0.0,22.6375,0.55
20,Fernando Alonso,Aston Martin,Honda,0.801217,21,Canada,5,0.0,22.6375,0.55
21,Lance Stroll,Aston Martin,Honda,0.747306,22,Canada,5,0.0,22.6375,0.55

========== ROUND 6 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Charles Leclerc,Ferrari,Ferrari,1.006555,1,Monaco,6,0.0,23.004167,0.4
1,George Russell,Mercedes,Mercedes,0.975542,2,Monaco,6,0.0,23.004167,0.4
2,Kimi Antonelli,Mercedes,Mercedes,0.961753,3,Monaco,6,0.0,23.004167,0.4
3,Oscar Piastri,McLaren,Mercedes,0.961709,4,Monaco,6,0.0,23.004167,0.4
4,Lewis Hamilton,Ferrari,Ferrari,0.950323,5,Monaco,6,0.0,23.004167,0.4
5,Pierre Gasly,Alpine,Mercedes,0.935198,6,Monaco,6,0.0,23.004167,0.4
6,Max Verstappen,Red Bull Racing,Red Bull Ford,0.930064,7,Monaco,6,0.0,23.004167,0.4
7,Oliver Bearman,Haas,Ferrari,0.917658,8,Monaco,6,0.0,23.004167,0.4
8,Franco Colapinto,Alpine,Mercedes,0.915719,9,Monaco,6,0.0,23.004167,0.4
9,Lando Norris,McLaren,Mercedes,0.908599,10,Monaco,6,0.0,23.004167,0.4
10,Esteban Ocon,Haas,Ferrari,0.892611,11,Monaco,6,0.0,23.004167,0.4
11,Sergio Perez,Cadillac,Ferrari,0.885144,12,Monaco,6,0.0,23.004167,0.4
12,Alex Albon,Williams,Mercedes,0.875836,13,Monaco,6,0.0,23.004167,0.4
13,Carlos Sainz,Williams,Mercedes,0.865170,14,Monaco,6,0.0,23.004167,0.4
14,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.860923,15,Monaco,6,0.0,23.004167,0.4
15,Gabriel Bortoleto,Audi,Audi,0.854836,16,Monaco,6,0.0,23.004167,0.4
16,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.847502,17,Monaco,6,0.0,23.004167,0.4
17,Nico Hulkenberg,Audi,Audi,0.843352,18,Monaco,6,0.0,23.004167,0.4
18,Liam Lawson,Racing Bulls,Red Bull Ford,0.833294,19,Monaco,6,0.0,23.004167,0.4
19,Valtteri Bottas,Cadillac,Ferrari,0.829186,20,Monaco,6,0.0,23.004167,0.4
20,Fernando Alonso,Aston Martin,Honda,0.802055,21,Monaco,6,0.0,23.004167,0.4
21,Lance Stroll,Aston Martin,Honda,0.747275,22,Monaco,6,0.0,23.004167,0.4

========== ROUND 7 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Oscar Piastri,McLaren,Mercedes,0.986576,1,Spain,7,0.0,22.0375,0.35
1,Kimi Antonelli,Mercedes,Mercedes,0.978984,2,Spain,7,0.0,22.0375,0.35
2,Charles Leclerc,Ferrari,Ferrari,0.978702,3,Spain,7,0.0,22.0375,0.35
3,George Russell,Mercedes,Mercedes,0.942525,4,Spain,7,0.0,22.0375,0.35
4,Lando Norris,McLaren,Mercedes,0.932542,5,Spain,7,0.0,22.0375,0.35
5,Max Verstappen,Red Bull Racing,Red Bull Ford,0.929081,6,Spain,7,0.0,22.0375,0.35
6,Pierre Gasly,Alpine,Mercedes,0.919908,7,Spain,7,0.0,22.0375,0.35
7,Lewis Hamilton,Ferrari,Ferrari,0.912680,8,Spain,7,0.0,22.0375,0.35
8,Liam Lawson,Racing Bulls,Red Bull Ford,0.903969,9,Spain,7,0.0,22.0375,0.35
9,Alex Albon,Williams,Mercedes,0.901313,10,Spain,7,0.0,22.0375,0.35
10,Carlos Sainz,Williams,Mercedes,0.898661,11,Spain,7,0.0,22.0375,0.35
11,Oliver Bearman,Haas,Ferrari,0.893018,12,Spain,7,0.0,22.0375,0.35
12,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.884454,13,Spain,7,0.0,22.0375,0.35
13,Esteban Ocon,Haas,Ferrari,0.882690,14,Spain,7,0.0,22.0375,0.35
14,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.881025,15,Spain,7,0.0,22.0375,0.35
15,Gabriel Bortoleto,Audi,Audi,0.874252,16,Spain,7,0.0,22.0375,0.35
16,Franco Colapinto,Alpine,Mercedes,0.865752,17,Spain,7,0.0,22.0375,0.35
17,Nico Hulkenberg,Audi,Audi,0.858080,18,Spain,7,0.0,22.0375,0.35
18,Valtteri Bottas,Cadillac,Ferrari,0.845758,19,Spain,7,0.0,22.0375,0.35
19,Sergio Perez,Cadillac,Ferrari,0.827747,20,Spain,7,0.0,22.0375,0.35
20,Fernando Alonso,Aston Martin,Honda,0.728098,21,Spain,7,0.0,22.0375,0.35
21,Lance Stroll,Aston Martin,Honda,0.727244,22,Spain,7,0.0,22.0375,0.35

========== ROUND 8 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Kimi Antonelli,Mercedes,Mercedes,1.055070,1,Austria,8,1.0,16.841667,0.5
1,Lewis Hamilton,Ferrari,Ferrari,1.029117,2,Austria,8,1.0,16.841667,0.5
2,Oscar Piastri,McLaren,Mercedes,1.022909,3,Austria,8,1.0,16.841667,0.5
3,George Russell,Mercedes,Mercedes,1.020264,4,Austria,8,1.0,16.841667,0.5
4,Charles Leclerc,Ferrari,Ferrari,1.002455,5,Austria,8,1.0,16.841667,0.5
5,Lando Norris,McLaren,Mercedes,0.996591,6,Austria,8,1.0,16.841667,0.5
6,Oliver Bearman,Haas,Ferrari,0.991243,7,Austria,8,1.0,16.841667,0.5
7,Max Verstappen,Red Bull Racing,Red Bull Ford,0.977668,8,Austria,8,1.0,16.841667,0.5
8,Pierre Gasly,Alpine,Mercedes,0.969119,9,Austria,8,1.0,16.841667,0.5
9,Carlos Sainz,Williams,Mercedes,0.968495,10,Austria,8,1.0,16.841667,0.5
10,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.940442,11,Austria,8,1.0,16.841667,0.5
11,Franco Colapinto,Alpine,Mercedes,0.934329,12,Austria,8,1.0,16.841667,0.5
12,Esteban Ocon,Haas,Ferrari,0.920525,13,Austria,8,1.0,16.841667,0.5
13,Nico Hulkenberg,Audi,Audi,0.916956,14,Austria,8,1.0,16.841667,0.5
14,Valtteri Bottas,Cadillac,Ferrari,0.910348,15,Austria,8,1.0,16.841667,0.5
15,Sergio Perez,Cadillac,Ferrari,0.907808,16,Austria,8,1.0,16.841667,0.5
16,Alex Albon,Williams,Mercedes,0.903864,17,Austria,8,1.0,16.841667,0.5
17,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.902395,18,Austria,8,1.0,16.841667,0.5
18,Liam Lawson,Racing Bulls,Red Bull Ford,0.899641,19,Austria,8,1.0,16.841667,0.5
19,Gabriel Bortoleto,Audi,Audi,0.879152,20,Austria,8,1.0,16.841667,0.5
20,Lance Stroll,Aston Martin,Honda,0.790834,21,Austria,8,1.0,16.841667,0.5
21,Fernando Alonso,Aston Martin,Honda,0.778351,22,Austria,8,1.0,16.841667,0.5

========== ROUND 9 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,George Russell,Mercedes,Mercedes,1.007817,1,Great Britain,9,0.0,25.0,0.7
1,Lewis Hamilton,Ferrari,Ferrari,0.971452,2,Great Britain,9,0.0,25.0,0.7
2,Alex Albon,Williams,Mercedes,0.960551,3,Great Britain,9,0.0,25.0,0.7
3,Lando Norris,McLaren,Mercedes,0.959359,4,Great Britain,9,0.0,25.0,0.7
4,Kimi Antonelli,Mercedes,Mercedes,0.953028,5,Great Britain,9,0.0,25.0,0.7
5,Oscar Piastri,McLaren,Mercedes,0.951441,6,Great Britain,9,0.0,25.0,0.7
6,Charles Leclerc,Ferrari,Ferrari,0.942863,7,Great Britain,9,0.0,25.0,0.7
7,Max Verstappen,Red Bull Racing,Red Bull Ford,0.930851,8,Great Britain,9,0.0,25.0,0.7
8,Pierre Gasly,Alpine,Mercedes,0.918556,9,Great Britain,9,0.0,25.0,0.7
9,Esteban Ocon,Haas,Ferrari,0.910609,10,Great Britain,9,0.0,25.0,0.7
10,Franco Colapinto,Alpine,Mercedes,0.878938,11,Great Britain,9,0.0,25.0,0.7
11,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.876067,12,Great Britain,9,0.0,25.0,0.7
12,Carlos Sainz,Williams,Mercedes,0.874312,13,Great Britain,9,0.0,25.0,0.7
13,Sergio Perez,Cadillac,Ferrari,0.859858,14,Great Britain,9,0.0,25.0,0.7
14,Valtteri Bottas,Cadillac,Ferrari,0.856357,15,Great Britain,9,0.0,25.0,0.7
15,Oliver Bearman,Haas,Ferrari,0.855592,16,Great Britain,9,0.0,25.0,0.7
16,Gabriel Bortoleto,Audi,Audi,0.844832,17,Great Britain,9,0.0,25.0,0.7
17,Liam Lawson,Racing Bulls,Red Bull Ford,0.838016,18,Great Britain,9,0.0,25.0,0.7
18,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.819970,19,Great Britain,9,0.0,25.0,0.7
19,Nico Hulkenberg,Audi,Audi,0.815944,20,Great Britain,9,0.0,25.0,0.7
20,Fernando Alonso,Aston Martin,Honda,0.738088,21,Great Britain,9,0.0,25.0,0.7
21,Lance Stroll,Aston Martin,Honda,0.728441,22,Great Britain,9,0.0,25.0,0.7

========== ROUND 10 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Oscar Piastri,McLaren,Mercedes,0.968494,1,Belgium,10,0.0,15.591667,0.7
1,Kimi Antonelli,Mercedes,Mercedes,0.951527,2,Belgium,10,0.0,15.591667,0.7
2,Charles Leclerc,Ferrari,Ferrari,0.947635,3,Belgium,10,0.0,15.591667,0.7
3,George Russell,Mercedes,Mercedes,0.946180,4,Belgium,10,0.0,15.591667,0.7
4,Lando Norris,McLaren,Mercedes,0.933236,5,Belgium,10,0.0,15.591667,0.7
5,Lewis Hamilton,Ferrari,Ferrari,0.931689,6,Belgium,10,0.0,15.591667,0.7
6,Oliver Bearman,Haas,Ferrari,0.923608,7,Belgium,10,0.0,15.591667,0.7
7,Max Verstappen,Red Bull Racing,Red Bull Ford,0.918635,8,Belgium,10,0.0,15.591667,0.7
8,Carlos Sainz,Williams,Mercedes,0.910366,9,Belgium,10,0.0,15.591667,0.7
9,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.906612,10,Belgium,10,0.0,15.591667,0.7
10,Gabriel Bortoleto,Audi,Audi,0.895048,11,Belgium,10,0.0,15.591667,0.7
11,Pierre Gasly,Alpine,Mercedes,0.892283,12,Belgium,10,0.0,15.591667,0.7
12,Nico Hulkenberg,Audi,Audi,0.888475,13,Belgium,10,0.0,15.591667,0.7
13,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.887894,14,Belgium,10,0.0,15.591667,0.7
14,Esteban Ocon,Haas,Ferrari,0.883048,15,Belgium,10,0.0,15.591667,0.7
15,Liam Lawson,Racing Bulls,Red Bull Ford,0.870312,16,Belgium,10,0.0,15.591667,0.7
16,Franco Colapinto,Alpine,Mercedes,0.868225,17,Belgium,10,0.0,15.591667,0.7
17,Alex Albon,Williams,Mercedes,0.866489,18,Belgium,10,0.0,15.591667,0.7
18,Valtteri Bottas,Cadillac,Ferrari,0.863221,19,Belgium,10,0.0,15.591667,0.7
19,Sergio Perez,Cadillac,Ferrari,0.805080,20,Belgium,10,0.0,15.591667,0.7
20,Fernando Alonso,Aston Martin,Honda,0.780256,21,Belgium,10,0.0,15.591667,0.7
21,Lance Stroll,Aston Martin,Honda,0.749778,22,Belgium,10,0.0,15.591667,0.7

========== ROUND 11 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Oscar Piastri,McLaren,Mercedes,0.996187,1,Hungary,11,0.0,23.008333,0.45
1,George Russell,Mercedes,Mercedes,0.979592,2,Hungary,11,0.0,23.008333,0.45
2,Charles Leclerc,Ferrari,Ferrari,0.957359,3,Hungary,11,0.0,23.008333,0.45
3,Kimi Antonelli,Mercedes,Mercedes,0.954180,4,Hungary,11,0.0,23.008333,0.45
4,Pierre Gasly,Alpine,Mercedes,0.948987,5,Hungary,11,0.0,23.008333,0.45
5,Lando Norris,McLaren,Mercedes,0.948360,6,Hungary,11,0.0,23.008333,0.45
6,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.935615,7,Hungary,11,0.0,23.008333,0.45
7,Max Verstappen,Red Bull Racing,Red Bull Ford,0.925162,8,Hungary,11,0.0,23.008333,0.45
8,Carlos Sainz,Williams,Mercedes,0.921342,9,Hungary,11,0.0,23.008333,0.45
9,Franco Colapinto,Alpine,Mercedes,0.911011,10,Hungary,11,0.0,23.008333,0.45
10,Alex Albon,Williams,Mercedes,0.904392,11,Hungary,11,0.0,23.008333,0.45
11,Lewis Hamilton,Ferrari,Ferrari,0.899995,12,Hungary,11,0.0,23.008333,0.45
12,Oliver Bearman,Haas,Ferrari,0.897934,13,Hungary,11,0.0,23.008333,0.45
13,Gabriel Bortoleto,Audi,Audi,0.889196,14,Hungary,11,0.0,23.008333,0.45
14,Esteban Ocon,Haas,Ferrari,0.860877,15,Hungary,11,0.0,23.008333,0.45
15,Sergio Perez,Cadillac,Ferrari,0.851608,16,Hungary,11,0.0,23.008333,0.45
16,Valtteri Bottas,Cadillac,Ferrari,0.844006,17,Hungary,11,0.0,23.008333,0.45
17,Nico Hulkenberg,Audi,Audi,0.841392,18,Hungary,11,0.0,23.008333,0.45
18,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.840273,19,Hungary,11,0.0,23.008333,0.45
19,Liam Lawson,Racing Bulls,Red Bull Ford,0.831593,20,Hungary,11,0.0,23.008333,0.45
20,Fernando Alonso,Aston Martin,Honda,0.797379,21,Hungary,11,0.0,23.008333,0.45
21,Lance Stroll,Aston Martin,Honda,0.750879,22,Hungary,11,0.0,23.008333,0.45

========== ROUND 12 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Lewis Hamilton,Ferrari,Ferrari,1.060493,1,Netherlands,12,1.0,17.554167,0.55
1,George Russell,Mercedes,Mercedes,1.021168,2,Netherlands,12,1.0,17.554167,0.55
2,Max Verstappen,Red Bull Racing,Red Bull Ford,1.010960,3,Netherlands,12,1.0,17.554167,0.55
3,Kimi Antonelli,Mercedes,Mercedes,0.999833,4,Netherlands,12,1.0,17.554167,0.55
4,Charles Leclerc,Ferrari,Ferrari,0.999055,5,Netherlands,12,1.0,17.554167,0.55
5,Oscar Piastri,McLaren,Mercedes,0.975035,6,Netherlands,12,1.0,17.554167,0.55
6,Oliver Bearman,Haas,Ferrari,0.964653,7,Netherlands,12,1.0,17.554167,0.55
7,Pierre Gasly,Alpine,Mercedes,0.963649,8,Netherlands,12,1.0,17.554167,0.55
8,Carlos Sainz,Williams,Mercedes,0.962859,9,Netherlands,12,1.0,17.554167,0.55
9,Lando Norris,McLaren,Mercedes,0.944111,10,Netherlands,12,1.0,17.554167,0.55
10,Esteban Ocon,Haas,Ferrari,0.940064,11,Netherlands,12,1.0,17.554167,0.55
11,Gabriel Bortoleto,Audi,Audi,0.934288,12,Netherlands,12,1.0,17.554167,0.55
12,Alex Albon,Williams,Mercedes,0.931238,13,Netherlands,12,1.0,17.554167,0.55
13,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.910926,14,Netherlands,12,1.0,17.554167,0.55
14,Liam Lawson,Racing Bulls,Red Bull Ford,0.907666,15,Netherlands,12,1.0,17.554167,0.55
15,Franco Colapinto,Alpine,Mercedes,0.905314,16,Netherlands,12,1.0,17.554167,0.55
16,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.902822,17,Netherlands,12,1.0,17.554167,0.55
17,Valtteri Bottas,Cadillac,Ferrari,0.883361,18,Netherlands,12,1.0,17.554167,0.55
18,Nico Hulkenberg,Audi,Audi,0.879032,19,Netherlands,12,1.0,17.554167,0.55
19,Sergio Perez,Cadillac,Ferrari,0.866710,20,Netherlands,12,1.0,17.554167,0.55
20,Fernando Alonso,Aston Martin,Honda,0.816095,21,Netherlands,12,1.0,17.554167,0.55
21,Lance Stroll,Aston Martin,Honda,0.803686,22,Netherlands,12,1.0,17.554167,0.55

========== ROUND 13 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Lando Norris,McLaren,Mercedes,0.986114,1,Italy,13,0.0,25.0,0.3
1,Charles Leclerc,Ferrari,Ferrari,0.973246,2,Italy,13,0.0,25.0,0.3
2,George Russell,Mercedes,Mercedes,0.973059,3,Italy,13,0.0,25.0,0.3
3,Kimi Antonelli,Mercedes,Mercedes,0.970397,4,Italy,13,0.0,25.0,0.3
4,Pierre Gasly,Alpine,Mercedes,0.970244,5,Italy,13,0.0,25.0,0.3
5,Lewis Hamilton,Ferrari,Ferrari,0.951324,6,Italy,13,0.0,25.0,0.3
6,Alex Albon,Williams,Mercedes,0.939099,7,Italy,13,0.0,25.0,0.3
7,Oscar Piastri,McLaren,Mercedes,0.932337,8,Italy,13,0.0,25.0,0.3
8,Esteban Ocon,Haas,Ferrari,0.930429,9,Italy,13,0.0,25.0,0.3
9,Max Verstappen,Red Bull Racing,Red Bull Ford,0.921290,10,Italy,13,0.0,25.0,0.3
10,Oliver Bearman,Haas,Ferrari,0.914082,11,Italy,13,0.0,25.0,0.3
11,Carlos Sainz,Williams,Mercedes,0.909433,12,Italy,13,0.0,25.0,0.3
12,Franco Colapinto,Alpine,Mercedes,0.906140,13,Italy,13,0.0,25.0,0.3
13,Liam Lawson,Racing Bulls,Red Bull Ford,0.889328,14,Italy,13,0.0,25.0,0.3
14,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.887198,15,Italy,13,0.0,25.0,0.3
15,Gabriel Bortoleto,Audi,Audi,0.871141,16,Italy,13,0.0,25.0,0.3
16,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.858537,17,Italy,13,0.0,25.0,0.3
17,Valtteri Bottas,Cadillac,Ferrari,0.858492,18,Italy,13,0.0,25.0,0.3
18,Nico Hulkenberg,Audi,Audi,0.848781,19,Italy,13,0.0,25.0,0.3
19,Sergio Perez,Cadillac,Ferrari,0.822298,20,Italy,13,0.0,25.0,0.3
20,Fernando Alonso,Aston Martin,Honda,0.763765,21,Italy,13,0.0,25.0,0.3
21,Lance Stroll,Aston Martin,Honda,0.689286,22,Italy,13,0.0,25.0,0.3

========== ROUND 14 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Kimi Antonelli,Mercedes,Mercedes,1.000799,1,Madrid,14,0.0,25.466667,0.4
1,George Russell,Mercedes,Mercedes,0.979829,2,Madrid,14,0.0,25.466667,0.4
2,Charles Leclerc,Ferrari,Ferrari,0.978349,3,Madrid,14,0.0,25.466667,0.4
3,Lando Norris,McLaren,Mercedes,0.958319,4,Madrid,14,0.0,25.466667,0.4
4,Oliver Bearman,Haas,Ferrari,0.927573,5,Madrid,14,0.0,25.466667,0.4
5,Lewis Hamilton,Ferrari,Ferrari,0.926452,6,Madrid,14,0.0,25.466667,0.4
6,Max Verstappen,Red Bull Racing,Red Bull Ford,0.925475,7,Madrid,14,0.0,25.466667,0.4
7,Oscar Piastri,McLaren,Mercedes,0.915987,8,Madrid,14,0.0,25.466667,0.4
8,Liam Lawson,Racing Bulls,Red Bull Ford,0.905288,9,Madrid,14,0.0,25.466667,0.4
9,Carlos Sainz,Williams,Mercedes,0.897999,10,Madrid,14,0.0,25.466667,0.4
10,Pierre Gasly,Alpine,Mercedes,0.892350,11,Madrid,14,0.0,25.466667,0.4
11,Franco Colapinto,Alpine,Mercedes,0.887477,12,Madrid,14,0.0,25.466667,0.4
12,Nico Hulkenberg,Audi,Audi,0.883047,13,Madrid,14,0.0,25.466667,0.4
13,Esteban Ocon,Haas,Ferrari,0.882052,14,Madrid,14,0.0,25.466667,0.4
14,Alex Albon,Williams,Mercedes,0.877527,15,Madrid,14,0.0,25.466667,0.4
15,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.876260,16,Madrid,14,0.0,25.466667,0.4
16,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.867880,17,Madrid,14,0.0,25.466667,0.4
17,Gabriel Bortoleto,Audi,Audi,0.862351,18,Madrid,14,0.0,25.466667,0.4
18,Valtteri Bottas,Cadillac,Ferrari,0.841132,19,Madrid,14,0.0,25.466667,0.4
19,Sergio Perez,Cadillac,Ferrari,0.825326,20,Madrid,14,0.0,25.466667,0.4
20,Fernando Alonso,Aston Martin,Honda,0.794671,21,Madrid,14,0.0,25.466667,0.4
21,Lance Stroll,Aston Martin,Honda,0.753929,22,Madrid,14,0.0,25.466667,0.4

========== ROUND 15 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,George Russell,Mercedes,Mercedes,1.036694,1,Azerbaijan,15,0.0,25.0,0.45
1,Kimi Antonelli,Mercedes,Mercedes,0.999511,2,Azerbaijan,15,0.0,25.0,0.45
2,Oscar Piastri,McLaren,Mercedes,0.985211,3,Azerbaijan,15,0.0,25.0,0.45
3,Charles Leclerc,Ferrari,Ferrari,0.979924,4,Azerbaijan,15,0.0,25.0,0.45
4,Carlos Sainz,Williams,Mercedes,0.957576,5,Azerbaijan,15,0.0,25.0,0.45
5,Lando Norris,McLaren,Mercedes,0.941008,6,Azerbaijan,15,0.0,25.0,0.45
6,Alex Albon,Williams,Mercedes,0.932275,7,Azerbaijan,15,0.0,25.0,0.45
7,Lewis Hamilton,Ferrari,Ferrari,0.930572,8,Azerbaijan,15,0.0,25.0,0.45
8,Max Verstappen,Red Bull Racing,Red Bull Ford,0.929538,9,Azerbaijan,15,0.0,25.0,0.45
9,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.908575,10,Azerbaijan,15,0.0,25.0,0.45
10,Esteban Ocon,Haas,Ferrari,0.903001,11,Azerbaijan,15,0.0,25.0,0.45
11,Oliver Bearman,Haas,Ferrari,0.895970,12,Azerbaijan,15,0.0,25.0,0.45
12,Gabriel Bortoleto,Audi,Audi,0.894003,13,Azerbaijan,15,0.0,25.0,0.45
13,Pierre Gasly,Alpine,Mercedes,0.892832,14,Azerbaijan,15,0.0,25.0,0.45
14,Sergio Perez,Cadillac,Ferrari,0.867667,15,Azerbaijan,15,0.0,25.0,0.45
15,Liam Lawson,Racing Bulls,Red Bull Ford,0.862655,16,Azerbaijan,15,0.0,25.0,0.45
16,Nico Hulkenberg,Audi,Audi,0.858697,17,Azerbaijan,15,0.0,25.0,0.45
17,Franco Colapinto,Alpine,Mercedes,0.858644,18,Azerbaijan,15,0.0,25.0,0.45
18,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.850701,19,Azerbaijan,15,0.0,25.0,0.45
19,Valtteri Bottas,Cadillac,Ferrari,0.804980,20,Azerbaijan,15,0.0,25.0,0.45
20,Fernando Alonso,Aston Martin,Honda,0.778274,21,Azerbaijan,15,0.0,25.0,0.45
21,Lance Stroll,Aston Martin,Honda,0.729677,22,Azerbaijan,15,0.0,25.0,0.45

========== ROUND 16 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Lando Norris,McLaren,Mercedes,1.047476,1,Singapore,16,1.0,27.729167,0.6
1,Kimi Antonelli,Mercedes,Mercedes,1.044336,2,Singapore,16,1.0,27.729167,0.6
2,Lewis Hamilton,Ferrari,Ferrari,1.023400,3,Singapore,16,1.0,27.729167,0.6
3,George Russell,Mercedes,Mercedes,1.020489,4,Singapore,16,1.0,27.729167,0.6
4,Charles Leclerc,Ferrari,Ferrari,1.018116,5,Singapore,16,1.0,27.729167,0.6
5,Oscar Piastri,McLaren,Mercedes,1.013212,6,Singapore,16,1.0,27.729167,0.6
6,Franco Colapinto,Alpine,Mercedes,0.975841,7,Singapore,16,1.0,27.729167,0.6
7,Max Verstappen,Red Bull Racing,Red Bull Ford,0.971962,8,Singapore,16,1.0,27.729167,0.6
8,Esteban Ocon,Haas,Ferrari,0.961066,9,Singapore,16,1.0,27.729167,0.6
9,Oliver Bearman,Haas,Ferrari,0.960950,10,Singapore,16,1.0,27.729167,0.6
10,Carlos Sainz,Williams,Mercedes,0.956640,11,Singapore,16,1.0,27.729167,0.6
11,Pierre Gasly,Alpine,Mercedes,0.949323,12,Singapore,16,1.0,27.729167,0.6
12,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.946249,13,Singapore,16,1.0,27.729167,0.6
13,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.935749,14,Singapore,16,1.0,27.729167,0.6
14,Nico Hulkenberg,Audi,Audi,0.902201,15,Singapore,16,1.0,27.729167,0.6
15,Valtteri Bottas,Cadillac,Ferrari,0.897700,16,Singapore,16,1.0,27.729167,0.6
16,Sergio Perez,Cadillac,Ferrari,0.887309,17,Singapore,16,1.0,27.729167,0.6
17,Alex Albon,Williams,Mercedes,0.877268,18,Singapore,16,1.0,27.729167,0.6
18,Fernando Alonso,Aston Martin,Honda,0.856372,19,Singapore,16,1.0,27.729167,0.6
19,Liam Lawson,Racing Bulls,Red Bull Ford,0.851105,20,Singapore,16,1.0,27.729167,0.6
20,Gabriel Bortoleto,Audi,Audi,0.840241,21,Singapore,16,1.0,27.729167,0.6
21,Lance Stroll,Aston Martin,Honda,0.835955,22,Singapore,16,1.0,27.729167,0.6

========== ROUND 17 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Lewis Hamilton,Ferrari,Ferrari,1.010905,1,USA Austin,17,0.0,25.0,0.45
1,Kimi Antonelli,Mercedes,Mercedes,0.991805,2,USA Austin,17,0.0,25.0,0.45
2,George Russell,Mercedes,Mercedes,0.989179,3,USA Austin,17,0.0,25.0,0.45
3,Charles Leclerc,Ferrari,Ferrari,0.939399,4,USA Austin,17,0.0,25.0,0.45
4,Lando Norris,McLaren,Mercedes,0.930902,5,USA Austin,17,0.0,25.0,0.45
5,Oliver Bearman,Haas,Ferrari,0.929701,6,USA Austin,17,0.0,25.0,0.45
6,Max Verstappen,Red Bull Racing,Red Bull Ford,0.915824,7,USA Austin,17,0.0,25.0,0.45
7,Carlos Sainz,Williams,Mercedes,0.899234,8,USA Austin,17,0.0,25.0,0.45
8,Esteban Ocon,Haas,Ferrari,0.891355,9,USA Austin,17,0.0,25.0,0.45
9,Oscar Piastri,McLaren,Mercedes,0.891212,10,USA Austin,17,0.0,25.0,0.45
10,Gabriel Bortoleto,Audi,Audi,0.882720,11,USA Austin,17,0.0,25.0,0.45
11,Nico Hulkenberg,Audi,Audi,0.879932,12,USA Austin,17,0.0,25.0,0.45
12,Pierre Gasly,Alpine,Mercedes,0.878992,13,USA Austin,17,0.0,25.0,0.45
13,Alex Albon,Williams,Mercedes,0.878422,14,USA Austin,17,0.0,25.0,0.45
14,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.877866,15,USA Austin,17,0.0,25.0,0.45
15,Valtteri Bottas,Cadillac,Ferrari,0.871667,16,USA Austin,17,0.0,25.0,0.45
16,Liam Lawson,Racing Bulls,Red Bull Ford,0.848145,17,USA Austin,17,0.0,25.0,0.45
17,Franco Colapinto,Alpine,Mercedes,0.845395,18,USA Austin,17,0.0,25.0,0.45
18,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.842919,19,USA Austin,17,0.0,25.0,0.45
19,Sergio Perez,Cadillac,Ferrari,0.833241,20,USA Austin,17,0.0,25.0,0.45
20,Fernando Alonso,Aston Martin,Honda,0.813725,21,USA Austin,17,0.0,25.0,0.45
21,Lance Stroll,Aston Martin,Honda,0.741702,22,USA Austin,17,0.0,25.0,0.45

========== ROUND 18 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Kimi Antonelli,Mercedes,Mercedes,1.073750,1,Mexico,18,1.0,18.65,0.5
1,Oscar Piastri,McLaren,Mercedes,1.060131,2,Mexico,18,1.0,18.65,0.5
2,George Russell,Mercedes,Mercedes,1.045410,3,Mexico,18,1.0,18.65,0.5
3,Charles Leclerc,Ferrari,Ferrari,0.998765,4,Mexico,18,1.0,18.65,0.5
4,Lewis Hamilton,Ferrari,Ferrari,0.992630,5,Mexico,18,1.0,18.65,0.5
5,Lando Norris,McLaren,Mercedes,0.988112,6,Mexico,18,1.0,18.65,0.5
6,Oliver Bearman,Haas,Ferrari,0.971319,7,Mexico,18,1.0,18.65,0.5
7,Pierre Gasly,Alpine,Mercedes,0.968896,8,Mexico,18,1.0,18.65,0.5
8,Carlos Sainz,Williams,Mercedes,0.962919,9,Mexico,18,1.0,18.65,0.5
9,Franco Colapinto,Alpine,Mercedes,0.957846,10,Mexico,18,1.0,18.65,0.5
10,Max Verstappen,Red Bull Racing,Red Bull Ford,0.943867,11,Mexico,18,1.0,18.65,0.5
11,Alex Albon,Williams,Mercedes,0.942254,12,Mexico,18,1.0,18.65,0.5
12,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.920655,13,Mexico,18,1.0,18.65,0.5
13,Liam Lawson,Racing Bulls,Red Bull Ford,0.918732,14,Mexico,18,1.0,18.65,0.5
14,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.916018,15,Mexico,18,1.0,18.65,0.5
15,Nico Hulkenberg,Audi,Audi,0.914022,16,Mexico,18,1.0,18.65,0.5
16,Gabriel Bortoleto,Audi,Audi,0.906769,17,Mexico,18,1.0,18.65,0.5
17,Valtteri Bottas,Cadillac,Ferrari,0.892908,18,Mexico,18,1.0,18.65,0.5
18,Esteban Ocon,Haas,Ferrari,0.884914,19,Mexico,18,1.0,18.65,0.5
19,Sergio Perez,Cadillac,Ferrari,0.859351,20,Mexico,18,1.0,18.65,0.5
20,Fernando Alonso,Aston Martin,Honda,0.806057,21,Mexico,18,1.0,18.65,0.5
21,Lance Stroll,Aston Martin,Honda,0.758128,22,Mexico,18,1.0,18.65,0.5

========== ROUND 19 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Charles Leclerc,Ferrari,Ferrari,1.029073,1,Brazil,19,0.0,15.891667,0.75
1,Kimi Antonelli,Mercedes,Mercedes,1.010651,2,Brazil,19,0.0,15.891667,0.75
2,George Russell,Mercedes,Mercedes,0.994406,3,Brazil,19,0.0,15.891667,0.75
3,Lewis Hamilton,Ferrari,Ferrari,0.952457,4,Brazil,19,0.0,15.891667,0.75
4,Lando Norris,McLaren,Mercedes,0.951395,5,Brazil,19,0.0,15.891667,0.75
5,Oscar Piastri,McLaren,Mercedes,0.942746,6,Brazil,19,0.0,15.891667,0.75
6,Franco Colapinto,Alpine,Mercedes,0.942591,7,Brazil,19,0.0,15.891667,0.75
7,Oliver Bearman,Haas,Ferrari,0.940992,8,Brazil,19,0.0,15.891667,0.75
8,Pierre Gasly,Alpine,Mercedes,0.930052,9,Brazil,19,0.0,15.891667,0.75
9,Esteban Ocon,Haas,Ferrari,0.927006,10,Brazil,19,0.0,15.891667,0.75
10,Alex Albon,Williams,Mercedes,0.926008,11,Brazil,19,0.0,15.891667,0.75
11,Max Verstappen,Red Bull Racing,Red Bull Ford,0.924433,12,Brazil,19,0.0,15.891667,0.75
12,Liam Lawson,Racing Bulls,Red Bull Ford,0.883375,13,Brazil,19,0.0,15.891667,0.75
13,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.877826,14,Brazil,19,0.0,15.891667,0.75
14,Sergio Perez,Cadillac,Ferrari,0.870349,15,Brazil,19,0.0,15.891667,0.75
15,Gabriel Bortoleto,Audi,Audi,0.867712,16,Brazil,19,0.0,15.891667,0.75
16,Valtteri Bottas,Cadillac,Ferrari,0.861248,17,Brazil,19,0.0,15.891667,0.75
17,Carlos Sainz,Williams,Mercedes,0.854735,18,Brazil,19,0.0,15.891667,0.75
18,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.845279,19,Brazil,19,0.0,15.891667,0.75
19,Nico Hulkenberg,Audi,Audi,0.830133,20,Brazil,19,0.0,15.891667,0.75
20,Fernando Alonso,Aston Martin,Honda,0.779703,21,Brazil,19,0.0,15.891667,0.75
21,Lance Stroll,Aston Martin,Honda,0.720500,22,Brazil,19,0.0,15.891667,0.75

========== ROUND 20 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,Charles Leclerc,Ferrari,Ferrari,0.997562,1,Las Vegas,20,0.0,34.5875,0.25
1,George Russell,Mercedes,Mercedes,0.979403,2,Las Vegas,20,0.0,34.5875,0.25
2,Kimi Antonelli,Mercedes,Mercedes,0.954471,3,Las Vegas,20,0.0,34.5875,0.25
3,Oscar Piastri,McLaren,Mercedes,0.949107,4,Las Vegas,20,0.0,34.5875,0.25
4,Max Verstappen,Red Bull Racing,Red Bull Ford,0.940639,5,Las Vegas,20,0.0,34.5875,0.25
5,Lando Norris,McLaren,Mercedes,0.919243,6,Las Vegas,20,0.0,34.5875,0.25
6,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.918446,7,Las Vegas,20,0.0,34.5875,0.25
7,Lewis Hamilton,Ferrari,Ferrari,0.917182,8,Las Vegas,20,0.0,34.5875,0.25
8,Oliver Bearman,Haas,Ferrari,0.900016,9,Las Vegas,20,0.0,34.5875,0.25
9,Carlos Sainz,Williams,Mercedes,0.893139,10,Las Vegas,20,0.0,34.5875,0.25
10,Esteban Ocon,Haas,Ferrari,0.891967,11,Las Vegas,20,0.0,34.5875,0.25
11,Pierre Gasly,Alpine,Mercedes,0.887306,12,Las Vegas,20,0.0,34.5875,0.25
12,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.880297,13,Las Vegas,20,0.0,34.5875,0.25
13,Alex Albon,Williams,Mercedes,0.875218,14,Las Vegas,20,0.0,34.5875,0.25
14,Nico Hulkenberg,Audi,Audi,0.873933,15,Las Vegas,20,0.0,34.5875,0.25
15,Franco Colapinto,Alpine,Mercedes,0.864720,16,Las Vegas,20,0.0,34.5875,0.25
16,Valtteri Bottas,Cadillac,Ferrari,0.857712,17,Las Vegas,20,0.0,34.5875,0.25
17,Sergio Perez,Cadillac,Ferrari,0.855961,18,Las Vegas,20,0.0,34.5875,0.25
18,Liam Lawson,Racing Bulls,Red Bull Ford,0.839406,19,Las Vegas,20,0.0,34.5875,0.25
19,Gabriel Bortoleto,Audi,Audi,0.827656,20,Las Vegas,20,0.0,34.5875,0.25
20,Fernando Alonso,Aston Martin,Honda,0.770750,21,Las Vegas,20,0.0,34.5875,0.25
21,Lance Stroll,Aston Martin,Honda,0.709289,22,Las Vegas,20,0.0,34.5875,0.25

========== ROUND 21 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,George Russell,Mercedes,Mercedes,0.998221,1,Qatar,21,0.0,36.970833,0.2
1,Charles Leclerc,Ferrari,Ferrari,0.960534,2,Qatar,21,0.0,36.970833,0.2
2,Kimi Antonelli,Mercedes,Mercedes,0.955960,3,Qatar,21,0.0,36.970833,0.2
3,Lewis Hamilton,Ferrari,Ferrari,0.955456,4,Qatar,21,0.0,36.970833,0.2
4,Oscar Piastri,McLaren,Mercedes,0.953598,5,Qatar,21,0.0,36.970833,0.2
5,Max Verstappen,Red Bull Racing,Red Bull Ford,0.935876,6,Qatar,21,0.0,36.970833,0.2
6,Pierre Gasly,Alpine,Mercedes,0.935544,7,Qatar,21,0.0,36.970833,0.2
7,Lando Norris,McLaren,Mercedes,0.931686,8,Qatar,21,0.0,36.970833,0.2
8,Alex Albon,Williams,Mercedes,0.908574,9,Qatar,21,0.0,36.970833,0.2
9,Liam Lawson,Racing Bulls,Red Bull Ford,0.906671,10,Qatar,21,0.0,36.970833,0.2
10,Oliver Bearman,Haas,Ferrari,0.899915,11,Qatar,21,0.0,36.970833,0.2
11,Franco Colapinto,Alpine,Mercedes,0.895175,12,Qatar,21,0.0,36.970833,0.2
12,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.894667,13,Qatar,21,0.0,36.970833,0.2
13,Gabriel Bortoleto,Audi,Audi,0.893952,14,Qatar,21,0.0,36.970833,0.2
14,Esteban Ocon,Haas,Ferrari,0.874025,15,Qatar,21,0.0,36.970833,0.2
15,Carlos Sainz,Williams,Mercedes,0.872426,16,Qatar,21,0.0,36.970833,0.2
16,Nico Hulkenberg,Audi,Audi,0.864002,17,Qatar,21,0.0,36.970833,0.2
17,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.862492,18,Qatar,21,0.0,36.970833,0.2
18,Sergio Perez,Cadillac,Ferrari,0.825094,19,Qatar,21,0.0,36.970833,0.2
19,Valtteri Bottas,Cadillac,Ferrari,0.822878,20,Qatar,21,0.0,36.970833,0.2
20,Fernando Alonso,Aston Martin,Honda,0.762672,21,Qatar,21,0.0,36.970833,0.2
21,Lance Stroll,Aston Martin,Honda,0.717085,22,Qatar,21,0.0,36.970833,0.2

========== ROUND 22 QUALIFYING ==========

,driver,team,engine_supplier,quali_score,quali_pos,circuit,round,rain_flag,avg_temp,weather_variability
0,George Russell,Mercedes,Mercedes,0.994313,1,Abu Dhabi,22,0.0,34.1375,0.2
1,Kimi Antonelli,Mercedes,Mercedes,0.974187,2,Abu Dhabi,22,0.0,34.1375,0.2
2,Oscar Piastri,McLaren,Mercedes,0.971813,3,Abu Dhabi,22,0.0,34.1375,0.2
3,Lando Norris,McLaren,Mercedes,0.947363,4,Abu Dhabi,22,0.0,34.1375,0.2
4,Lewis Hamilton,Ferrari,Ferrari,0.940773,5,Abu Dhabi,22,0.0,34.1375,0.2
5,Charles Leclerc,Ferrari,Ferrari,0.931470,6,Abu Dhabi,22,0.0,34.1375,0.2
6,Arvid Lindblad,Racing Bulls,Red Bull Ford,0.913778,7,Abu Dhabi,22,0.0,34.1375,0.2
7,Max Verstappen,Red Bull Racing,Red Bull Ford,0.899350,8,Abu Dhabi,22,0.0,34.1375,0.2
8,Oliver Bearman,Haas,Ferrari,0.897495,9,Abu Dhabi,22,0.0,34.1375,0.2
9,Carlos Sainz,Williams,Mercedes,0.891776,10,Abu Dhabi,22,0.0,34.1375,0.2
10,Isak Hadjar,Red Bull Racing,Red Bull Ford,0.890789,11,Abu Dhabi,22,0.0,34.1375,0.2
11,Franco Colapinto,Alpine,Mercedes,0.889775,12,Abu Dhabi,22,0.0,34.1375,0.2
12,Pierre Gasly,Alpine,Mercedes,0.889261,13,Abu Dhabi,22,0.0,34.1375,0.2
13,Esteban Ocon,Haas,Ferrari,0.888722,14,Abu Dhabi,22,0.0,34.1375,0.2
14,Gabriel Bortoleto,Audi,Audi,0.887093,15,Abu Dhabi,22,0.0,34.1375,0.2
15,Alex Albon,Williams,Mercedes,0.877545,16,Abu Dhabi,22,0.0,34.1375,0.2
16,Nico Hulkenberg,Audi,Audi,0.874586,17,Abu Dhabi,22,0.0,34.1375,0.2
17,Sergio Perez,Cadillac,Ferrari,0.836729,18,Abu Dhabi,22,0.0,34.1375,0.2
18,Liam Lawson,Racing Bulls,Red Bull Ford,0.829932,19,Abu Dhabi,22,0.0,34.1375,0.2
19,Valtteri Bottas,Cadillac,Ferrari,0.817280,20,Abu Dhabi,22,0.0,34.1375,0.2
20,Fernando Alonso,Aston Martin,Honda,0.780859,21,Abu Dhabi,22,0.0,34.1375,0.2
21,Lance Stroll,Aston Martin,Honda,0.720381,22,Abu Dhabi,22,0.0,34.1375,0.2

In [26]:
driver_df, con_df = compute_expected_standings(
    season_results,
    n_simulations=1000
)

In [27]:
import os

os.makedirs("deepnote_output", exist_ok=True)

driver_df.to_csv("deepnote_output/driver_standings.csv", index=False)
con_df.to_csv("deepnote_output/constructor_standings.csv", index=False)
all_quali.to_csv("deepnote_output/all_qualifying_predictions.csv", index=False)

for rnd in sorted(k for k in season_results.keys() if isinstance(k, int)):
    season_results[rnd]["summary"].to_csv(
        f"deepnote_output/race_summary_round_{rnd}.csv",
        index=False
    )
    season_results[rnd]["probabilities"].to_csv(
        f"deepnote_output/race_probabilities_round_{rnd}.csv",
        index=False
    )

print("Saved to deepnote_output/")

Saved to deepnote_output/

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a48761f7-46b0-4a39-ac60-090ae77a0ccc' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>